
var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.Yf||(g.Yf=0);g.Yf++;
(function(a){function b(n,t,r){var u=new XMLHttpRequest;u.open("GET",n,!0);u.responseType="arraybuffer";u.onprogress=function(w){var y=t;w.total&&(y=w.total);if(w.loaded){u.pf?g.yf[n].loaded=w.loaded:(u.pf=!0,g.yf||(g.yf={}),g.yf[n]={loaded:w.loaded,total:y});var B=y=w=0,D;for(D in g.yf){var I=g.yf[D];w+=I.total;y+=I.loaded;B++}w=Math.ceil(w*g.Yf/B);g.setStatus&&g.setStatus("Downloading data... ("+y+"/"+w+")")}else!g.yf&&g.setStatus&&g.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+
n);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)r(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}function c(n){console.error("package error:",n)}function d(){function n(w,y,B){this.start=w;this.ag=y;this.audio=B}function t(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);n.prototype.Mg=w;w=a.files;for(var y=0;y<
w.length;++y)n.prototype.pf[w[y].filename].onload();g.removeRunDependency("datafile_build/web/index.data")}g.FS_createPath("/","assets",!0,!0);n.prototype={pf:{},open:function(w,y){this.name=y;this.pf[y]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Lg(this.Mg.subarray(this.start,this.ag))},Lg:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.pf[this.name]=null}};for(var r=a.files,u=0;u<r.length;++u)(new n(r[u].start,
r[u].end,r[u].audio)).open("GET",r[u].filename);g.addRunDependency("datafile_build/web/index.data");g.tg||(g.tg={});g.tg["build/web/index.data"]={dh:!1};l?(t(l),l=null):k=t}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,h("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,k=null,l=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;l||b(e,f,function(n){k?(k(n),k=null):l=n},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/assets/font.ttf",
start:0,end:26216,audio:0},{filename:"/assets/atlas.dat",start:26216,end:26807,audio:0},{filename:"/assets/atlas.png",start:26807,end:130267,audio:0}],remote_package_size:130267,package_uuid:"1f817aee-7e7a-45bd-b386-c6c421cc6afc"});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;
ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var m="",ka,la,ma,na,oa;
if(ia)m=ha?require("path").dirname(m)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",
p),ea=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?m=self.location.href:"undefined"!==typeof document&&document.currentScript&&(m=document.currentScript.src),m=0!==m.indexOf("blob:")?m.substr(0,m.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=g.print||console.log.bind(console),h=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);function ra(a){sa||(sa={});sa[a]||(sa[a]=1,h(a))}var sa,ta;g.wasmBinary&&(ta=g.wasmBinary);
var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&p("no native wasm support detected");
function ua(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":va[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":x=[b>>>0,(z=b,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];v[a>>2]=x[0];v[a+4>>2]=x[1];break;case "float":A[a>>2]=b;break;case "double":wa[a>>3]=b;break;default:p("invalid type for setValue: "+c)}}var xa,ya=!1;
function assert(a,b){a||p("Assertion failed: "+b)}function za(a){var b=Aa(a.length);a.subarray||a.slice?C.set(a,b):C.set(new Uint8Array(a),b);return b}var Ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ca(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function E(a,b){return a?Ca(C,a,b):""}
function F(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ea(a){var b=Da(a)+1,c=Fa(b);F(a,q,c,b);return c}var Ha,q,C,va,Ia,v,G,A,wa;
function Ja(){var a=xa.buffer;Ha=a;g.HEAP8=q=new Int8Array(a);g.HEAP16=va=new Int16Array(a);g.HEAP32=v=new Int32Array(a);g.HEAPU8=C=new Uint8Array(a);g.HEAPU16=Ia=new Uint16Array(a);g.HEAPU32=G=new Uint32Array(a);g.HEAPF32=A=new Float32Array(a);g.HEAPF64=wa=new Float64Array(a)}var H,Ka=[],La=[],Ma=[],Na=[];La.push({mg:function(){Oa()}});function Pa(){var a=g.preRun.shift();Ka.unshift(a)}var Qa=0,Ra=null,Sa=null;function Ta(){Qa++;g.monitorRunDependencies&&g.monitorRunDependencies(Qa)}
function Ua(){Qa--;g.monitorRunDependencies&&g.monitorRunDependencies(Qa);if(0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa)){var a=Sa;Sa=null;a()}}g.preloadedImages={};g.preloadedAudios={};function p(a){if(g.onAbort)g.onAbort(a);h(a);ya=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Va(a){var b=Wa;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Xa(){return Va("data:application/octet-stream;base64,")}
var Wa="index.wasm";if(!Xa()){var Ya=Wa;Wa=g.locateFile?g.locateFile(Ya,m):m+Ya}function Za(){var a=Wa;try{if(a==Wa&&ta)return new Uint8Array(ta);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function $a(){if(!ta&&(fa||ha)){if("function"===typeof fetch&&!Va("file://"))return fetch(Wa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Wa+"'";return a.arrayBuffer()}).catch(function(){return Za()});if(la)return new Promise(function(a,b){la(Wa,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Za()})}
var z,x,bb={29191:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},29357:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},29583:function(a){var b=g.SDL2;if(a){void 0!==b.capture.Ef&&clearTimeout(b.capture.Ef);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.nf&&(b.capture.nf.onaudioprocess=function(){},b.capture.nf.disconnect(),b.capture.nf=void 0);void 0!==b.capture.Lf&&(b.capture.Lf.disconnect(),b.capture.Lf=void 0);void 0!==b.capture.Rf&&(b.capture.Rf=void 0);b.capture=void 0}else void 0!=b.audio.nf&&(b.audio.nf.disconnect(),b.audio.nf=void 0),b.audio=void 0;void 0!==b.lf&&void 0===b.audio&&void 0===b.capture&&(b.lf.close(),b.lf=void 0)},30755:function(a){"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;
a?b.capture={}:b.audio={};b.lf||("undefined"!==typeof AudioContext?b.lf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.lf=new webkitAudioContext),b.lf&&ab(b.lf));return void 0===b.lf?-1:0},31308:function(){return g.SDL2.lf.sampleRate},31378:function(a,b,c,d){function e(){}function f(l){void 0!==k.capture.Ef&&(clearTimeout(k.capture.Ef),k.capture.Ef=void 0);k.capture.Lf=k.lf.createMediaStreamSource(l);k.capture.nf=k.lf.createScriptProcessor(b,a,1);k.capture.nf.onaudioprocess=function(n){void 0!==
k&&void 0!==k.capture&&(n.outputBuffer.getChannelData(0).fill(0),k.capture.Uf=n.inputBuffer,n=[d],H.get(c).apply(null,n))};k.capture.Lf.connect(k.capture.nf);k.capture.nf.connect(k.lf.destination);k.capture.stream=l}var k=g.SDL2;k.capture.Rf=k.lf.createBuffer(a,b,k.lf.sampleRate);k.capture.Rf.getChannelData(0).fill(0);k.capture.Ef=setTimeout(function(){k.capture.Uf=k.capture.Rf;var l=[d];H.get(c).apply(null,l)},b/k.lf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},33030:function(a,b,c,d){var e=g.SDL2;e.audio.nf=e.lf.createScriptProcessor(b,0,a);e.audio.nf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.jg=f.outputBuffer,f=[d],H.get(c).apply(null,f))};e.audio.nf.connect(e.lf.destination)},33440:function(a,b){for(var c=g.SDL2,d=c.audio.jg.numberOfChannels,e=0;e<d;++e){var f=c.audio.jg.getChannelData(e);
if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var k=0;k<b;++k)f[k]=A[a+(k*d+e<<2)>>2]}},33920:function(a,b){for(var c=g.SDL2,d=c.capture.Uf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Uf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var k=0;k<b;++k)ua(a+4*k,f[k],"float");else for(k=0;k<b;++k)ua(a+
4*(k*d+e),f[k],"float")}}};function cb(a,b,c){a.addEventListener(b,c,{once:!0})}function ab(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&cb(d,c,function(){"suspended"===a.state&&a.resume()})})})}function db(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.mg;"number"===typeof c?void 0===b.Ff?H.get(c)():H.get(c)(b.Ff):c(void 0===b.Ff?null:b.Ff)}}}
function eb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function J(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function hb(a){if("/"===a)return"/";a=J(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ib(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){p("randomDevice")}}
function jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],output:[],Af:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new K(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Af.flush(a.tty)},flush:function(a){a.tty.Af.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Af.ng)throw new K(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.Af.ng(a.tty)}catch(l){throw new K(29);}if(void 0===k&&0===e)throw new K(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Af.dg)throw new K(60);
try{for(var e=0;e<d;e++)a.tty.Af.dg(a.tty,b[c+e])}catch(f){throw new K(29);}d&&(a.node.timestamp=Date.now());return e}},pb={ng:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.pf?Buffer.pf(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ob(b,!0)}return a.input.shift()},dg:function(a,b){null===b||10===b?(qa(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ca(a.output,0)),a.output=[])}},qb={dg:function(a,b){null===b||10===b?(h(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Ca(a.output,0)),a.output=[])}},L={uf:null,vf:function(){return L.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new K(63);L.uf||(L.uf={dir:{node:{tf:L.hf.tf,qf:L.hf.qf,lookup:L.hf.lookup,Mf:L.hf.Mf,rename:L.hf.rename,unlink:L.hf.unlink,rmdir:L.hf.rmdir,readdir:L.hf.readdir,symlink:L.hf.symlink},stream:{wf:L.jf.wf}},file:{node:{tf:L.hf.tf,qf:L.hf.qf},stream:{wf:L.jf.wf,read:L.jf.read,write:L.jf.write,fg:L.jf.fg,Nf:L.jf.Nf,Pf:L.jf.Pf}},link:{node:{tf:L.hf.tf,qf:L.hf.qf,readlink:L.hf.readlink},stream:{}},ig:{node:{tf:L.hf.tf,
qf:L.hf.qf},stream:rb}});c=sb(a,b,c,d);M(c.mode)?(c.hf=L.uf.dir.node,c.jf=L.uf.dir.stream,c.gf={}):32768===(c.mode&61440)?(c.hf=L.uf.file.node,c.jf=L.uf.file.stream,c.kf=0,c.gf=null):40960===(c.mode&61440)?(c.hf=L.uf.link.node,c.jf=L.uf.link.stream):8192===(c.mode&61440)&&(c.hf=L.uf.ig.node,c.jf=L.uf.ig.stream);c.timestamp=Date.now();a&&(a.gf[b]=c,a.timestamp=c.timestamp);return c},eh:function(a){if(a.gf&&a.gf.subarray){for(var b=[],c=0;c<a.kf;++c)b.push(a.gf[c]);return b}return a.gf},fh:function(a){return a.gf?
a.gf.subarray?a.gf.subarray(0,a.kf):new Uint8Array(a.gf):new Uint8Array(0)},kg:function(a,b){var c=a.gf?a.gf.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.gf,a.gf=new Uint8Array(b),0<a.kf&&a.gf.set(c.subarray(0,a.kf),0))},Tg:function(a,b){if(a.kf!=b)if(0==b)a.gf=null,a.kf=0;else{if(!a.gf||a.gf.subarray){var c=a.gf;a.gf=new Uint8Array(b);c&&a.gf.set(c.subarray(0,Math.min(b,a.kf)))}else if(a.gf||(a.gf=[]),a.gf.length>b)a.gf.length=b;else for(;a.gf.length<b;)a.gf.push(0);
a.kf=b}},hf:{tf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;M(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.kf:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Dg=4096;b.blocks=Math.ceil(b.size/b.Dg);return b},qf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&
L.Tg(a,b.size)},lookup:function(){throw tb[44];},Mf:function(a,b,c,d){return L.createNode(a,b,c,d)},rename:function(a,b,c){if(M(a.mode)){try{var d=ub(b,c)}catch(f){}if(d)for(var e in d.gf)throw new K(55);}delete a.parent.gf[a.name];a.parent.timestamp=Date.now();a.name=c;b.gf[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.gf[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=ub(a,b),d;for(d in c.gf)throw new K(55);delete a.gf[b];a.timestamp=Date.now()},readdir:function(a){var b=
[".",".."],c;for(c in a.gf)a.gf.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new K(28);return a.link}},jf:{read:function(a,b,c,d,e){var f=a.node.gf;if(e>=a.node.kf)return 0;a=Math.min(a.node.kf-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();
if(b.subarray&&(!a.gf||a.gf.subarray)){if(f)return a.gf=b.subarray(c,c+d),a.kf=d;if(0===a.kf&&0===e)return a.gf=b.slice(c,c+d),a.kf=d;if(e+d<=a.kf)return a.gf.set(b.subarray(c,c+d),e),d}L.kg(a,e+d);if(a.gf.subarray&&b.subarray)a.gf.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.gf[e+f]=b[c+f];a.kf=Math.max(a.kf,e+d);return d},wf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.kf);if(0>b)throw new K(28);return b},fg:function(a,b,c){L.kg(a.node,b+c);a.node.kf=Math.max(a.node.kf,
b+c)},Nf:function(a,b,c,d,e,f){if(0!==b)throw new K(28);if(32768!==(a.node.mode&61440))throw new K(43);a=a.node.gf;if(f&2||a.buffer!==Ha){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=Aa(f);c<f;)q[b+c++]=0;c=b;if(!c)throw new K(48);q.set(a,c)}else d=!1,c=a.byteOffset;return{Rg:c,Tf:d}},Pf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new K(43);if(e&2)return 0;L.jf.write(a,b,0,d,c,!1);return 0}}},vb=null,wb=
{},xb=[],yb=1,zb=null,Ab=!0,Bb={},K=null,tb={};
function Cb(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={lg:!0,eg:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.eg)throw new K(32);a=eb(a.split("/").filter(function(k){return!!k}),!1);var e=vb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=ub(e,a[d]);c=J(c+"/"+a[d]);e.Df&&(!f||f&&b.lg)&&(e=e.Df.root);if(!f||b.If)for(f=0;40960===(e.mode&61440);)if(e=Db(c),c=jb(gb(c),e),e=Cb(c,{eg:b.eg}).node,40<f++)throw new K(32);}return{path:c,node:e}}
function Eb(a){for(var b;;){if(a===a.parent)return a=a.vf.rg,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length}function ub(a,b){var c;if(c=(c=Gb(a,"x"))?c:a.hf.lookup?0:2)throw new K(c,a);for(c=zb[Fb(a.id,b)];c;c=c.zf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.hf.lookup(a,b)}
function sb(a,b,c,d){a=new Hb(a,b,c,d);b=Fb(a.parent.id,a.name);a.zf=zb[b];return zb[b]=a}function M(a){return 16384===(a&61440)}var Ib={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Gb(a,b){if(Ab)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Kb(a,b){try{return ub(a,b),20}catch(c){}return Gb(a,"wx")}
function Lb(a){var b=4096;for(a=a||0;a<=b;a++)if(!xb[a])return a;throw new K(33);}function Mb(a,b){Nb||(Nb=function(){},Nb.prototype={});var c=new Nb,d;for(d in a)c[d]=a[d];a=c;b=Lb(b);a.fd=b;return xb[b]=a}var rb={open:function(a){a.jf=wb[a.node.rdev].jf;a.jf.open&&a.jf.open(a)},wf:function(){throw new K(70);}};function mb(a,b){wb[a]={jf:b}}
function Ob(a,b){var c="/"===b,d=!b;if(c&&vb)throw new K(10);if(!c&&!d){var e=Cb(b,{lg:!1});b=e.path;e=e.node;if(e.Df)throw new K(10);if(!M(e.mode))throw new K(54);}b={type:a,mh:{},rg:b,Pg:[]};a=a.vf(b);a.vf=b;b.root=a;c?vb=a:e&&(e.Df=b,e.vf&&e.vf.Pg.push(b))}function Pb(a,b,c){var d=Cb(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new K(28);var e=Kb(d,a);if(e)throw new K(e);if(!d.hf.Mf)throw new K(63);return d.hf.Mf(d,a,b,c)}function Qb(a){return Pb(a,16895,0)}
function Rb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Pb(a,b|8192,c)}function Sb(a,b){if(!jb(a))throw new K(44);var c=Cb(b,{parent:!0}).node;if(!c)throw new K(44);b=hb(b);var d=Kb(c,b);if(d)throw new K(d);if(!c.hf.symlink)throw new K(63);c.hf.symlink(c,b,a)}
function Tb(a){var b=Cb(a,{parent:!0}).node,c=hb(a),d=ub(b,c);a:{try{var e=ub(b,c)}catch(k){e=k.mf;break a}var f=Gb(b,"wx");e=f?f:M(e.mode)?31:0}if(e)throw new K(e);if(!b.hf.unlink)throw new K(63);if(d.Df)throw new K(10);try{Bb.willDeletePath&&Bb.willDeletePath(a)}catch(k){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.hf.unlink(b,c);b=Fb(d.parent.id,d.name);if(zb[b]===d)zb[b]=d.zf;else for(b=zb[b];b;){if(b.zf===d){b.zf=d.zf;break}b=b.zf}try{if(Bb.onDeletePath)Bb.onDeletePath(a)}catch(k){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Db(a){a=Cb(a).node;if(!a)throw new K(44);if(!a.hf.readlink)throw new K(28);return jb(Eb(a.parent),a.hf.readlink(a))}function Ub(a,b){var c;"string"===typeof a?c=Cb(a,{If:!0}).node:c=a;if(!c.hf.qf)throw new K(63);c.hf.qf(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Vb(a,b,c,d){if(""===a)throw new K(44);if("string"===typeof b){var e=Ib[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=J(a);try{f=Cb(a,{If:!(b&131072)}).node}catch(l){}}e=!1;if(b&64)if(f){if(b&128)throw new K(20);}else f=Pb(a,c,0),e=!0;if(!f)throw new K(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!M(f.mode))throw new K(54);if(!e&&(c=f?40960===(f.mode&61440)?32:M(f.mode)&&
("r"!==Jb(b)||b&512)?31:Gb(f,Jb(b)):44))throw new K(c);if(b&512){c=f;var k;"string"===typeof c?k=Cb(c,{If:!0}).node:k=c;if(!k.hf.qf)throw new K(63);if(M(k.mode))throw new K(31);if(32768!==(k.mode&61440))throw new K(28);if(c=Gb(k,"w"))throw new K(c);k.hf.qf(k,{size:0,timestamp:Date.now()})}b&=-131713;d=Mb({node:f,path:Eb(f),flags:b,seekable:!0,position:0,jf:f.jf,Vg:[],error:!1},d);d.jf.open&&d.jf.open(d);!g.logReadFiles||b&1||(Wb||(Wb={}),a in Wb||(Wb[a]=1,h("FS.trackingDelegate error on read file: "+
a)));try{Bb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Bb.onOpenFile(a,f))}catch(l){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function Xb(a){if(null===a.fd)throw new K(8);a.$f&&(a.$f=null);try{a.jf.close&&a.jf.close(a)}catch(b){throw b;}finally{xb[a.fd]=null}a.fd=null}
function Yb(a,b,c){if(null===a.fd)throw new K(8);if(!a.seekable||!a.jf.wf)throw new K(70);if(0!=c&&1!=c&&2!=c)throw new K(28);a.position=a.jf.wf(a,b,c);a.Vg=[]}
function Zb(a,b,c,d,e,f){if(0>d||0>e)throw new K(28);if(null===a.fd)throw new K(8);if(0===(a.flags&2097155))throw new K(8);if(M(a.node.mode))throw new K(31);if(!a.jf.write)throw new K(28);a.seekable&&a.flags&1024&&Yb(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new K(70);b=a.jf.write(a,b,c,d,e,f);k||(a.position+=b);try{if(a.path&&Bb.onWriteToFile)Bb.onWriteToFile(a.path)}catch(l){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function $b(){K||(K=function(a,b){this.node=b;this.Ug=function(c){this.mf=c};this.Ug(a);this.message="FS error"},K.prototype=Error(),K.prototype.constructor=K,[44].forEach(function(a){tb[a]=new K(a);tb[a].stack="<generic error, no stack>"}))}var ac;function bc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function cc(a,b){a="string"===typeof a?a:Eb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=J(a+"/"+c);try{Qb(d)}catch(e){}a=d}}return d}
function dc(a,b,c,d){a=J(("string"===typeof a?a:Eb(a))+"/"+b);c=bc(c,d);return Pb(a,(void 0!==c?c:438)&4095|32768,0)}function ec(a,b,c,d,e,f){a=b?J(("string"===typeof a?a:Eb(a))+"/"+b):a;d=bc(d,e);e=Pb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Ub(e,d|146);a=Vb(e,577);Zb(a,c,0,c.length,0,f);Xb(a);Ub(e,d)}return e}
function fc(a,b,c,d){a=J(("string"===typeof a?a:Eb(a))+"/"+b);b=bc(!!c,!!d);fc.pg||(fc.pg=64);var e=fc.pg++<<8|0;mb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,k,l,n){for(var t=0,r=0;r<n;r++){try{var u=c()}catch(w){throw new K(29);}if(void 0===u&&0===t)throw new K(6);if(null===u||void 0===u)break;t++;k[l+r]=u}t&&(f.node.timestamp=Date.now());return t},write:function(f,k,l,n){for(var t=0;t<n;t++)try{d(k[l+t])}catch(r){throw new K(29);}n&&
(f.node.timestamp=Date.now());return t}});return Rb(a,b,e)}function hc(a){if(!(a.Jg||a.Kg||a.link||a.gf)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.gf=ob(ka(a.url),!0),a.kf=a.gf.length}catch(b){throw new K(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function ic(a,b,c,d,e){function f(){this.bg=!1;this.pf=[]}f.prototype.get=function(r){if(!(r>this.length-1||0>r)){var u=r%this.chunkSize;return this.og(r/this.chunkSize|0)[u]}};f.prototype.ag=function(r){this.og=r};f.prototype.gg=function(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var u=Number(r.getResponseHeader("Content-length")),w,y=(w=r.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;r=(w=r.getResponseHeader("Content-Encoding"))&&"gzip"===w;var B=1048576;y||(B=u);var D=this;D.ag(function(I){var fb=I*B,Ga=(I+1)*B-1;Ga=Math.min(Ga,u-1);if("undefined"===typeof D.pf[I]){var pe=D.pf;if(fb>Ga)throw Error("invalid range ("+fb+", "+Ga+") or no bytes requested!");if(Ga>u-1)throw Error("only "+u+" bytes available! programmer error!");var R=new XMLHttpRequest;R.open("GET",c,!1);u!==B&&R.setRequestHeader("Range","bytes="+fb+"-"+Ga);"undefined"!=typeof Uint8Array&&(R.responseType=
"arraybuffer");R.overrideMimeType&&R.overrideMimeType("text/plain; charset=x-user-defined");R.send(null);if(!(200<=R.status&&300>R.status||304===R.status))throw Error("Couldn't load "+c+". Status: "+R.status);fb=void 0!==R.response?new Uint8Array(R.response||[]):ob(R.responseText||"",!0);pe[I]=fb}if("undefined"===typeof D.pf[I])throw Error("doXHR failed!");return D.pf[I]});if(r||!u)B=u=1,B=u=this.og(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Cg=
u;this.Bg=B;this.bg=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.bg||this.gg();return this.Cg}},chunkSize:{get:function(){this.bg||this.gg();return this.Bg}}});var l=void 0}else l=c,k=void 0;var n=dc(a,b,d,e);k?n.gf=k:l&&(n.gf=null,n.url=l);Object.defineProperties(n,{kf:{get:function(){return this.gf.length}}});
var t={};Object.keys(n.jf).forEach(function(r){var u=n.jf[r];t[r]=function(){hc(n);return u.apply(null,arguments)}});t.read=function(r,u,w,y,B){hc(n);r=r.node.gf;if(B>=r.length)return 0;y=Math.min(r.length-B,y);if(r.slice)for(var D=0;D<y;D++)u[w+D]=r[B+D];else for(D=0;D<y;D++)u[w+D]=r.get(B+D);return y};n.jf=t;return n}
function jc(a,b,c,d,e,f,k,l,n,t){function r(y){function B(I){t&&t();l||ec(a,b,I,d,e,n);f&&f();Ua(w)}var D=!1;g.preloadPlugins.forEach(function(I){!D&&I.canHandle(u)&&(I.handle(y,u,B,function(){k&&k();Ua(w)}),D=!0)});D||B(y)}kc();var u=b?jb(J(a+"/"+b)):a,w="cp "+u;Ta(w);"string"==typeof c?lc(c,function(y){r(y)},k):r(c)}var N={},Nb,Wb,mc={};
function nc(a,b){try{var c=Cb(a,{If:!0}).node;if(!c)throw new K(44);if(!c.hf.tf)throw new K(63);var d=c.hf.tf(c)}catch(e){if(e&&e.node&&J(a)!==J(Eb(e.node)))return-54;throw e;}v[b>>2]=d.dev;v[b+4>>2]=0;v[b+8>>2]=d.ino;v[b+12>>2]=d.mode;v[b+16>>2]=d.nlink;v[b+20>>2]=d.uid;v[b+24>>2]=d.gid;v[b+28>>2]=d.rdev;v[b+32>>2]=0;x=[d.size>>>0,(z=d.size,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];v[b+40>>2]=x[0];v[b+44>>2]=x[1];v[b+
48>>2]=4096;v[b+52>>2]=d.blocks;v[b+56>>2]=d.atime.getTime()/1E3|0;v[b+60>>2]=0;v[b+64>>2]=d.mtime.getTime()/1E3|0;v[b+68>>2]=0;v[b+72>>2]=d.ctime.getTime()/1E3|0;v[b+76>>2]=0;x=[d.ino>>>0,(z=d.ino,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];v[b+80>>2]=x[0];v[b+84>>2]=x[1];return 0}var oc=void 0;function pc(){oc+=4;return v[oc-4>>2]}function qc(a){a=xb[a];if(!a)throw new K(8);return a}var rc;
ia?rc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?rc=dateNow:rc=function(){return performance.now()};function sc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,k){b.drawElementsInstancedANGLE(c,d,e,f,k)})}
function tc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function uc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var vc=1,wc=[],O=[],xc=[],yc=[],zc=[],P=[],Q=[],Ac=[],Bc=[],S=[],Cc=[],T=[],Dc=[],Ec=[],Fc={},Gc={},Hc={},Ic=4;function U(a){Jc||(Jc=a)}function Kc(a){for(var b=vc++,c=a.length;c<b;c++)a[c]=null;return b}function Lc(a,b){if(a=1<b.qg?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=Kc(Bc),d={gh:c,attributes:b,version:b.qg,Sf:a};a.canvas&&(a.canvas.Xg=d);Bc[c]=d;("undefined"===typeof b.Fg||b.Fg)&&Mc(d);b=c}else b=0;return b}
function Mc(a){a||(a=V);if(!a.Hg){a.Hg=!0;var b=a.Sf;sc(b);tc(b);uc(b);b.ah=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.hh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.rf=b.getExtension("EXT_disjoint_timer_query");b.kh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var Nc={},Jc,V,Oc=[];
function Pc(a,b,c,d){for(var e=0;e<a;e++){var f=W[c](),k=f&&Kc(d);f?(f.name=k,d[k]=f):U(1282);v[b+4*e>>2]=k}}function Qc(a,b,c,d,e,f,k,l){b=O[b];if(a=W[a](b,c))d=l&&F(a.name,C,l,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),k&&(v[k>>2]=a.type)}function Rc(a,b){G[a>>2]=b;G[a+4>>2]=(b-G[a>>2])/4294967296}
function Sc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=W.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>V.version){U(1282);return}d=2*(W.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>V.version){U(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=W.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){U(1280);
h("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:U(1280);h("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Rc(b,d);break;case 0:v[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else U(1281)}
function Tc(a,b,c,d){if(c){b=W.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:U(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{U(1280);return}break;default:U(1280);return}switch(d){case 1:Rc(c,a);break;case 0:v[c>>2]=a;break;case 2:A[c>>2]=a;break;case 4:q[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else U(1281)}
function Uc(a){var b=Da(a)+1,c=Aa(b);F(a,C,c,b);return c}function Vc(a,b,c,d){if(c)if(a=W.getUniform(O[a],P[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else U(1281)}
function Wc(a,b,c,d){if(c)if(a=W.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else U(1281)}function Xc(a){a-=5120;return 0==a?q:1==a?C:2==a?va:4==a?v:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?G:Ia}
function Yc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Zc(a,b,c,d,e){a=Xc(a);var f=Yc(a),k=Ic;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+k-1&-k)>>f)}var $c=[],ad=[],bd=null,cd=0,dd=null,ed=0,fd=0,gd=0,hd=0,id=[],jd={},kd,ld,md,nd=!1,od=!1,pd=[];
function kc(){function a(){od=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!qd){qd=!0;try{rd=!0}catch(c){rd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}sd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:rd?null:console.log("warning: no BlobBuilder");
td="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.sg||"undefined"!==typeof td||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.sg=!0);g.preloadPlugins.push({canHandle:function(c){return!g.sg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var k=null;if(rd)try{k=new Blob([c],{type:ud(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:ud(d)}))}catch(t){ra("Blob constructor present but fails: "+
t+"; falling back to blob builder")}k||(k=new sd,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var l=td.createObjectURL(k),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=n.width;t.height=n.height;t.getContext("2d").drawImage(n,0,0);g.preloadedImages[d]=t;td.revokeObjectURL(l);e&&e(c)};n.onerror=function(){console.log("Image "+l+" could not be decoded");f&&f()};n.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.lh&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function k(u){n||(n=!0,g.preloadedAudios[d]=u,e&&e(c))}function l(){n||(n=!0,g.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(rd){try{var t=new Blob([c],{type:ud(d)})}catch(u){return l()}t=td.createObjectURL(t);var r=new Audio;r.addEventListener("canplaythrough",function(){k(r)},!1);r.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",w=0,y=0,
B=0;B<c.length;B++)for(w=w<<8|c[B],y+=8;6<=y;){var D=w>>y-6&63;y-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}2==y?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],u+="=="):4==y&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],u+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+u;k(r)}};r.src=t;vd(function(){k(r)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!od&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function wd(a,b,c,d){if(b&&g.xf&&a==g.canvas)return g.xf;var e;if(b){var f={antialias:!1,alpha:!1,qg:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!==typeof Nc&&(e=Lc(a,f)))var l=Bc[e].Sf}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof W,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.xf=l,b&&(V=Bc[e],g.xf=W=V&&V.Sf),g.nh=b,pd.forEach(function(n){n()}),kc());return l}
var xd=!1,yd=void 0,zd=void 0;
function Ad(a,b){function c(){nd=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Bd,yd&&d.requestPointerLock(),nd=!0,zd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=G[SDL.screen>>2]|8388608),Cd(g.canvas),Dd()):Cd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),zd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=G[SDL.screen>>2]&
-8388609),Cd(g.canvas),Dd()):Cd(d));if(g.onFullScreen)g.onFullScreen(nd);if(g.onFullscreen)g.onFullscreen(nd)}yd=a;zd=b;"undefined"===typeof yd&&(yd=!0);"undefined"===typeof zd&&(zd=!1);var d=g.canvas;xd||(xd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Bd(){if(!nd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Ed=0;function Fd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ed)Ed=b+1E3/60;else for(;b+2>=Ed;)Ed+=1E3/60;setTimeout(a,Math.max(Ed-b,0))}}function vd(a){noExitRuntime=!0;setTimeout(function(){ya||a()},1E4)}
function ud(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Gd=0,Hd=0,Id=0,Jd=0;
function Kd(a){if(od)"mousemove"!=a.type&&"mozMovementX"in a?Id=Jd=0:(Id=a.movementX||a.mozMovementX||a.webkitMovementX||0,Jd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Gd=SDL.ih+Id,Hd=SDL.jh+Jd):(Gd+=Id,Hd+=Jd);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Id=e-Gd,Jd=a-Hd,Gd=e,Hd=a)}}function lc(a,b,c){var d="al "+a;la(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ua(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ta(d)}var Ld=[];function Dd(){var a=g.canvas;Ld.forEach(function(b){b(a.width,a.height)})}function Md(a,b,c){Cd(g.canvas,a,b);c||Dd()}
function Cd(a,b,c){b&&c?(a.Wg=b,a.Gg=c):(b=a.Wg,c=a.Gg);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}zd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var qd,rd,sd,td;
function Nd(a,b){fd=a;gd=b;if(dd)if(0==a)bd=function(){var d=Math.max(0,ld+b-rc())|0;setTimeout(md,d)};else if(1==a)bd=function(){Fd(md)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}bd=function(){setImmediate(md)}}}
function Od(a,b,c,d,e){noExitRuntime=!0;assert(!dd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");dd=a;ed=d;var f=cd;md=function(){if(!ya)if(0<id.length){var k=Date.now(),l=id.shift();l.mg(l.Ff);if(kd){var n=kd,t=0==n%1?n-1:Math.floor(n);kd=l.$g?t:(8*n+(t+.5))/9}console.log('main loop blocker "'+l.name+'" took '+(Date.now()-k)+" ms");g.setStatus&&(k=g.statusMessage||
"Please wait...",l=kd,n=jd.bh,l?l<n?g.setStatus(k+" ("+(n-l)+"/"+n+")"):g.setStatus(k):g.setStatus(""));f<cd||setTimeout(md,0)}else if(!(f<cd))if(hd=hd+1|0,1==fd&&1<gd&&0!=hd%gd)bd();else{0==fd&&(ld=rc());a:if(!(ya||g.preMainLoop&&!1===g.preMainLoop())){try{a()}catch(r){if(r instanceof pa||"unwind"==r)break a;r&&"object"===typeof r&&r.stack&&h("exception thrown: "+[r,r.stack]);throw r;}g.postMainLoop&&g.postMainLoop()}f<cd||("object"===typeof SDL&&SDL.audio&&SDL.audio.Sg&&SDL.audio.Sg(),bd())}};e||
(b&&0<b?Nd(0,1E3/b):Nd(1,1),bd());if(c)throw"unwind";}var Pd={};function Qd(){if(!Rd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Pd)a[b]=Pd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Rd=c}return Rd}var Rd;
function Sd(a,b,c,d){this.id=a;this.y=this.x=0;this.Zf=!1;this.xg=this.wg=0;this.width=b;this.height=c;this.vg=b;this.ug=c;this.title=d;this.attributes=Td;this.buttons=0;this.keys=[];this.Wf=[];this.hg=this.Kf=this.Xf=this.Qf=this.Gf=this.Hf=this.Of=this.Jf=this.zg=this.Ag=this.title=null}function Ud(a){return 0>=a||!X?null:X[a-1]}
var Vd=null,Y=null,X=null,Td=null,Wd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Xd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Yd(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Zd(a){Y&&Y.hg&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||H.get(Y.hg)(Y.id,a))}
function $d(a,b){if(Y){var c=Xd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Wf[a]=b;Y.Kf&&(d&&(b=2),H.get(Y.Kf)(Y.id,c,a,b,Yd()))}}}function ae(){be()}function ce(){be()}function de(a){$d(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function ee(a){$d(a.keyCode,0)}function fe(){if(Y)for(var a=0;a<Y.Wf.length;++a)Y.Wf[a]&&$d(a,0)}function ge(a){Y&&(Kd(a),a.target==g.canvas&&Y.Hf&&H.get(Y.Hf)(Y.id,Gd,Hd))}function he(a){Y&&a.target==g.canvas&&Y.Gf&&H.get(Y.Gf)(Y.id,1)}
function ie(a){Y&&a.target==g.canvas&&Y.Gf&&H.get(Y.Gf)(Y.id,0)}function je(a,b){if(Y&&(Kd(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.Of&&H.get(Y.Of)(Y.id,c,b,Yd())}}function ke(a){Y&&je(a,1)}function le(a){Y&&je(a,0)}
function me(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Qf&&a.target==g.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;H.get(Y.Qf)(Y.id,b,c);a.preventDefault()}}var ne={},oe=null,qe=null;
function be(){if(hd!==qe||!hd){oe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;qe=hd;for(var a=0;a<oe.length;++a){var b=oe[a];if(b){ne[a]||(console.log("glfw joystick connected:",a),ne[a]={id:za(ob(b.id)),Zg:b.buttons.length,Yg:b.axes.length,buttons:za(Array(b.buttons.length)),axes:za(Array(4*b.axes.length))});for(var c=ne[a],d=0;d<b.buttons.length;++d)ua(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)ua(c.axes+4*d,
b.axes[d],"float")}else ne[a]&&(console.log("glfw joystick disconnected",a),re(ne[a].id),re(ne[a].buttons),re(ne[a].axes),delete ne[a])}}}
function se(a){function b(l){var n="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(u){if(2!=t.readyState)++f,console.log("failed to read dropped file: "+l.name+": "+t.error);else{var w=new Uint8Array(u.target.result);var y=y||{};y.flags=y.flags||577;u=Vb(n,y.flags,y.mode);if("string"===typeof w){var B=new Uint8Array(Da(w)+1);w=F(w,B,0,B.length);Zb(u,B,0,w,void 0,y.Eg)}else if(ArrayBuffer.isView(w))Zb(u,w,0,w.byteLength,void 0,y.Eg);else throw Error("Unsupported data type");
Xb(u);if(++f===e){H.get(Y.Xf)(Y.id,e,c);for(y=0;y<d.length;++y)re(d[y]);re(c)}}};t.readAsArrayBuffer(l);var r=za(ob(n));d.push(r);ua(c+4*k,r,"i8*")}if(Y&&Y.Xf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=za(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,f=0;cc("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function te(a){if(Y&&Y.Xf)return a.preventDefault(),!1}var ue=[];
function Hb(a,b,c,d){a||(a=this);this.parent=a;this.vf=a.vf;this.Df=null;this.id=yb++;this.name=b;this.mode=c;this.hf={};this.jf={};this.rdev=d}Object.defineProperties(Hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Kg:{get:function(){return M(this.mode)}},Jg:{get:function(){return 8192===(this.mode&61440)}}});$b();zb=Array(4096);
Ob(L,"/");Qb("/tmp");Qb("/home");Qb("/home/web_user");(function(){Qb("/dev");mb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Rb("/dev/null",259);lb(1280,pb);lb(1536,qb);Rb("/dev/tty",1280);Rb("/dev/tty1",1536);var a=ib();fc("/dev","random",a);fc("/dev","urandom",a);Qb("/dev/shm");Qb("/dev/shm/tmp")})();
(function(){Qb("/proc");var a=Qb("/proc/self");Qb("/proc/self/fd");Ob({vf:function(){var b=sb(a,"fd",16895,73);b.hf={lookup:function(c,d){var e=xb[+d];if(!e)throw new K(8);c={parent:null,vf:{rg:"fake"},hf:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=cc;g.FS_createDataFile=ec;g.FS_createPreloadedFile=jc;g.FS_createLazyFile=ic;g.FS_createDevice=fc;g.FS_unlink=Tb;for(var W,Z=0;32>Z;++Z)Oc.push(Array(Z));var ve=new Float32Array(288);
for(Z=0;288>Z;++Z)$c[Z]=ve.subarray(0,Z+1);var we=new Int32Array(288);for(Z=0;288>Z;++Z)ad[Z]=we.subarray(0,Z+1);g.requestFullscreen=function(a,b){Ad(a,b)};g.requestAnimationFrame=function(a){Fd(a)};g.setCanvasSize=function(a,b,c){Md(a,b,c)};g.pauseMainLoop=function(){bd=null;cd++};g.resumeMainLoop=function(){cd++;var a=fd,b=gd,c=dd;dd=null;Od(c,0,!1,ed,!0);Nd(a,b);bd()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
g.createContext=function(a,b,c,d){return wd(a,b,c,d)};function ob(a,b){var c=Array(Da(a)+1);a=F(a,c,0,c.length);b&&(c.length=a);return c}
var Ce={b:function(a,b,c,d){p("Assertion failed: "+E(a)+", at: "+[b?E(b):"unknown filename",c,d?E(d):"unknown function"])},n:function(a,b,c){oc=c;try{var d=qc(a);switch(b){case 0:var e=pc();return 0>e?-28:Vb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=pc(),d.flags|=e,0;case 12:return e=pc(),va[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return v[xe()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof N&&f instanceof K||
p(f),-f.mf}},Ga:function(a,b){try{var c=qc(a);return nc(c.path,b)}catch(d){return"undefined"!==typeof N&&d instanceof K||p(d),-d.mf}},Ha:function(a,b,c){oc=c;try{var d=qc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=pc();return v[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=pc();if(!d.jf.Ig)throw new K(59);return d.jf.Ig(d,b,a);case 21523:return d.tty?0:-59;
case 21524:return d.tty?0:-59;default:p("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof N&&f instanceof K||p(f),-f.mf}},Fa:function(a,b,c,d,e,f){try{a:{f<<=12;var k=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var n=ye(16384,b);if(!n){l=-48;break a}ze(n,0,b);k=!0}else{var t=xb[e];if(!t){l=-8;break a}var r=f;if(0!==(c&2)&&0===(d&2)&&2!==(t.flags&2097155))throw new K(2);if(1===(t.flags&2097155))throw new K(2);if(!t.jf.Nf)throw new K(43);var u=t.jf.Nf(t,a,b,r,c,d);n=u.Rg;
k=u.Tf}mc[n]={Og:n,Ng:b,Tf:k,fd:e,Qg:c,flags:d,offset:f};l=n}}return l}catch(w){return"undefined"!==typeof N&&w instanceof K||p(w),-w.mf}},Ea:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=mc[a];if(d&&b===d.Ng){var e=xb[d.fd];if(e&&d.Qg&2){var f=d.flags,k=d.offset,l=C.slice(a,a+b);e&&e.jf.Pf&&e.jf.Pf(e,l,k,b,f)}mc[a]=null;d.Tf&&re(d.Og)}c=0}return c}catch(n){return"undefined"!==typeof N&&n instanceof K||p(n),-n.mf}},Ya:function(a,b,c){oc=c;try{var d=E(a),e=c?pc():0;return Vb(d,b,e).fd}catch(f){return"undefined"!==
typeof N&&f instanceof K||p(f),-f.mf}},l:function(a,b){try{return a=E(a),nc(a,b)}catch(c){return"undefined"!==typeof N&&c instanceof K||p(c),-c.mf}},ya:function(){p()},i:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=rc();else return v[xe()>>2]=28,-1;v[b>>2]=a/1E3|0;v[b+4>>2]=a%1E3*1E6|0;return 0},c:function(a,b,c){ue.length=0;var d;for(c>>=2;d=C[b++];)(d=105>d)&&c&1&&c++,ue.push(d?wa[c++>>1]:v[c]),++c;return bb[a].apply(null,ue)},ba:function(a){W.activeTexture(a)},aa:function(a,b){W.attachShader(O[a],
Q[b])},uc:function(a,b){W.beginQuery(a,Cc[b])},ta:function(a,b){W.rf.beginQueryEXT(a,S[b])},bc:function(a){W.beginTransformFeedback(a)},$:function(a,b,c){W.bindAttribLocation(O[a],b,E(c))},_:function(a,b){35051==a?W.Vf=b:35052==a&&(W.sf=b);W.bindBuffer(a,wc[b])},_b:function(a,b,c){W.bindBufferBase(a,b,wc[c])},$b:function(a,b,c,d,e){W.bindBufferRange(a,b,wc[c],d,e)},Z:function(a,b){W.bindFramebuffer(a,xc[b])},Y:function(a,b){W.bindRenderbuffer(a,yc[b])},fb:function(a,b){W.bindSampler(a,T[b])},X:function(a,
b){W.bindTexture(a,zc[b])},Za:function(a,b){W.bindTransformFeedback(a,Dc[b])},gc:function(a){W.bindVertexArray(Ac[a])},ka:function(a){W.bindVertexArray(Ac[a])},V:function(a,b,c,d){W.blendColor(a,b,c,d)},U:function(a){W.blendEquation(a)},T:function(a,b){W.blendEquationSeparate(a,b)},S:function(a,b){W.blendFunc(a,b)},R:function(a,b,c,d){W.blendFuncSeparate(a,b,c,d)},jc:function(a,b,c,d,e,f,k,l,n,t){W.blitFramebuffer(a,b,c,d,e,f,k,l,n,t)},Q:function(a,b,c,d){2<=V.version?c?W.bufferData(a,C,d,c,b):W.bufferData(a,
b,d):W.bufferData(a,c?C.subarray(c,c+b):b,d)},P:function(a,b,c,d){2<=V.version?W.bufferSubData(a,b,C,d,c):W.bufferSubData(a,b,C.subarray(d,d+c))},O:function(a){return W.checkFramebufferStatus(a)},N:function(a){W.clear(a)},Db:function(a,b,c,d){W.clearBufferfi(a,b,c,d)},Eb:function(a,b,c){W.clearBufferfv(a,b,A,c>>2)},Gb:function(a,b,c){W.clearBufferiv(a,b,v,c>>2)},Fb:function(a,b,c){W.clearBufferuiv(a,b,G,c>>2)},M:function(a,b,c,d){W.clearColor(a,b,c,d)},K:function(a){W.clearDepth(a)},J:function(a){W.clearStencil(a)},
pb:function(a,b,c,d){return W.clientWaitSync(Ec[a],b,(c>>>0)+4294967296*d)},I:function(a,b,c,d){W.colorMask(!!a,!!b,!!c,!!d)},H:function(a){W.compileShader(Q[a])},G:function(a,b,c,d,e,f,k,l){2<=V.version?W.sf?W.compressedTexImage2D(a,b,c,d,e,f,k,l):W.compressedTexImage2D(a,b,c,d,e,f,C,l,k):W.compressedTexImage2D(a,b,c,d,e,f,l?C.subarray(l,l+k):null)},Ac:function(a,b,c,d,e,f,k,l,n){W.sf?W.compressedTexImage3D(a,b,c,d,e,f,k,l,n):W.compressedTexImage3D(a,b,c,d,e,f,k,C,n,l)},F:function(a,b,c,d,e,f,k,
l,n){2<=V.version?W.sf?W.compressedTexSubImage2D(a,b,c,d,e,f,k,l,n):W.compressedTexSubImage2D(a,b,c,d,e,f,k,C,n,l):W.compressedTexSubImage2D(a,b,c,d,e,f,k,n?C.subarray(n,n+l):null)},zc:function(a,b,c,d,e,f,k,l,n,t,r){W.sf?W.compressedTexSubImage3D(a,b,c,d,e,f,k,l,n,t,r):W.compressedTexSubImage3D(a,b,c,d,e,f,k,l,n,C,r,t)},Bb:function(a,b,c,d,e){W.copyBufferSubData(a,b,c,d,e)},E:function(a,b,c,d,e,f,k,l){W.copyTexImage2D(a,b,c,d,e,f,k,l)},D:function(a,b,c,d,e,f,k,l){W.copyTexSubImage2D(a,b,c,d,e,f,
k,l)},Bc:function(a,b,c,d,e,f,k,l,n){W.copyTexSubImage3D(a,b,c,d,e,f,k,l,n)},C:function(){var a=Kc(O),b=W.createProgram();b.name=a;O[a]=b;return a},B:function(a){var b=Kc(Q);Q[b]=W.createShader(a);return b},z:function(a){W.cullFace(a)},y:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=wc[d];e&&(W.deleteBuffer(e),e.name=0,wc[d]=null,d==W.Vf&&(W.Vf=0),d==W.sf&&(W.sf=0))}},x:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=xc[d];e&&(W.deleteFramebuffer(e),e.name=0,xc[d]=null)}},w:function(a){if(a){var b=
O[a];b?(W.deleteProgram(b),b.name=0,O[a]=null,Fc[a]=null):U(1281)}},wc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Cc[d];e&&(W.deleteQuery(e),Cc[d]=null)}},va:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(W.rf.deleteQueryEXT(e),S[d]=null)}},v:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=yc[d];e&&(W.deleteRenderbuffer(e),e.name=0,yc[d]=null)}},ib:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=T[d];e&&(W.deleteSampler(e),e.name=0,T[d]=null)}},u:function(a){if(a){var b=
Q[a];b?(W.deleteShader(b),Q[a]=null):U(1281)}},qb:function(a){if(a){var b=Ec[a];b?(W.deleteSync(b),b.name=0,Ec[a]=null):U(1281)}},t:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=zc[d];e&&(W.deleteTexture(e),e.name=0,zc[d]=null)}},Xa:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Dc[d];e&&(W.deleteTransformFeedback(e),e.name=0,Dc[d]=null)}},fc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];W.deleteVertexArray(Ac[d]);Ac[d]=null}},ja:function(a,b){for(var c=0;c<a;c++){var d=v[b+
4*c>>2];W.deleteVertexArray(Ac[d]);Ac[d]=null}},s:function(a){W.depthFunc(a)},r:function(a){W.depthMask(!!a)},q:function(a,b){W.depthRange(a,b)},Ue:function(a,b){W.detachShader(O[a],Q[b])},Te:function(a){W.disable(a)},Se:function(a){W.disableVertexAttribArray(a)},Re:function(a,b,c){W.drawArrays(a,b,c)},ub:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},ea:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Lc:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Mc:function(a,b,c,d){W.drawArraysInstanced(a,
b,c,d)},Ja:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},qc:function(a,b){for(var c=Oc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},Gc:function(a,b){for(var c=Oc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},ga:function(a,b){for(var c=Oc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},Qe:function(a,b,c,d){W.drawElements(a,b,c,d)},tb:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},da:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Hc:function(a,b,c,d,e){W.drawElementsInstanced(a,
b,c,d,e)},Ic:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Kc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Ec:function(a,b,c,d,e,f){W.drawElements(a,d,e,f)},Pe:function(a){W.enable(a)},Oe:function(a){W.enableVertexAttribArray(a)},tc:function(a){W.endQuery(a)},sa:function(a){W.rf.endQueryEXT(a)},ac:function(){W.endTransformFeedback()},sb:function(a,b){return(a=W.fenceSync(a,b))?(b=Kc(Ec),a.name=b,Ec[b]=a,b):0},Ne:function(){W.finish()},Me:function(){W.flush()},Le:function(a,b,
c,d){W.framebufferRenderbuffer(a,b,c,yc[d])},Je:function(a,b,c,d,e){W.framebufferTexture2D(a,b,c,zc[d],e)},hc:function(a,b,c,d,e){W.framebufferTextureLayer(a,b,zc[c],d,e)},Ie:function(a){W.frontFace(a)},He:function(a,b){Pc(a,b,"createBuffer",wc)},Fe:function(a,b){Pc(a,b,"createFramebuffer",xc)},xc:function(a,b){Pc(a,b,"createQuery",Cc)},wa:function(a,b){for(var c=0;c<a;c++){var d=W.rf.createQueryEXT();if(!d){for(U(1282);c<a;)v[b+4*c++>>2]=0;break}var e=Kc(S);d.name=e;S[e]=d;v[b+4*c>>2]=e}},Ee:function(a,
b){Pc(a,b,"createRenderbuffer",yc)},jb:function(a,b){Pc(a,b,"createSampler",T)},De:function(a,b){Pc(a,b,"createTexture",zc)},Wa:function(a,b){Pc(a,b,"createTransformFeedback",Dc)},ec:function(a,b){Pc(a,b,"createVertexArray",Ac)},ia:function(a,b){Pc(a,b,"createVertexArray",Ac)},Ge:function(a){W.generateMipmap(a)},Ce:function(a,b,c,d,e,f,k){Qc("getActiveAttrib",a,b,c,d,e,f,k)},Be:function(a,b,c,d,e,f,k){Qc("getActiveUniform",a,b,c,d,e,f,k)},wb:function(a,b,c,d,e){a=O[a];if(a=W.getActiveUniformBlockName(a,
b))e&&0<c?(c=F(a,C,e,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0)},xb:function(a,b,c,d){if(d)switch(a=O[a],c){case 35393:a=W.getActiveUniformBlockName(a,b);v[d>>2]=a.length+1;break;default:if(a=W.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)v[d>>2]=a;else for(b=0;b<a.length;b++)v[d+4*b>>2]=a[b]}else U(1281)},zb:function(a,b,c,d,e){if(e)if(0<b&&0==c)U(1281);else{a=O[a];for(var f=[],k=0;k<b;k++)f.push(v[c+4*k>>2]);if(a=W.getActiveUniforms(a,f,d))for(b=a.length,k=0;k<b;k++)v[e+4*k>>2]=a[k]}else U(1281)},
Ae:function(a,b,c,d){a=W.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=Q.indexOf(a[b])},ye:function(a,b){return W.getAttribLocation(O[a],E(b))},xe:function(a,b){Sc(a,b,4)},kb:function(a,b,c){c?Rc(c,W.getBufferParameter(a,b)):U(1281)},we:function(a,b,c){c?v[c>>2]=W.getBufferParameter(a,b):U(1281)},ve:function(){var a=W.getError()||Jc;Jc=0;return a},ue:function(a,b){Sc(a,b,2)},Pb:function(a,b){return W.getFragDataLocation(O[a],E(b))},te:function(a,b,c,d){a=
W.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},lb:function(a,b,c){Tc(a,b,c,1)},nb:function(a,b){Sc(a,b,1)},cc:function(a,b,c){Tc(a,b,c,0)},se:function(a,b){Sc(a,b,0)},La:function(a,b,c,d,e){if(0>d)U(1281);else if(e){if(a=W.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)v[e+b>>2]=a[b]}else U(1281)},Sa:function(){U(1282)},qe:function(a,b,c,d){a=W.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");
b=0<b&&d?F(a,C,d,b):0;c&&(v[c>>2]=b)},re:function(a,b,c){if(c)if(a>=vc)U(1281);else{var d=Fc[a];if(d)if(35716==b)a=W.getProgramInfoLog(O[a]),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b)v[c>>2]=d.cg;else if(35722==b){if(-1==d.Bf){a=O[a];var e=W.getProgramParameter(a,35721);for(b=d.Bf=0;b<e;++b)d.Bf=Math.max(d.Bf,W.getActiveAttrib(a,b).name.length+1)}v[c>>2]=d.Bf}else if(35381==b){if(-1==d.Cf)for(a=O[a],e=W.getProgramParameter(a,35382),b=d.Cf=0;b<e;++b)d.Cf=Math.max(d.Cf,W.getActiveUniformBlockName(a,
b).length+1);v[c>>2]=d.Cf}else v[c>>2]=W.getProgramParameter(O[a],b);else U(1282)}else U(1281)},ma:function(a,b,c){if(c){a=W.rf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Rc(c,d)}else U(1281)},oa:function(a,b,c){if(c){a=W.rf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else U(1281)},la:function(a,b,c){if(c){a=W.rf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Rc(c,d)}else U(1281)},rc:function(a,b,c){if(c){a=W.getQueryParameter(Cc[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else U(1281)},na:function(a,b,c){if(c){a=W.rf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else U(1281)},sc:function(a,b,c){c?v[c>>2]=W.getQuery(a,b):U(1281)},pa:function(a,b,c){c?v[c>>2]=W.rf.getQueryEXT(a,b):U(1281)},pe:function(a,b,c){c?v[c>>2]=W.getRenderbufferParameter(a,b):U(1281)},$a:function(a,b,c){c?(a=T[a],A[c>>2]=W.getSamplerParameter(a,b)):U(1281)},ab:function(a,b,c){c?(a=T[a],v[c>>2]=W.getSamplerParameter(a,
b)):U(1281)},ne:function(a,b,c,d){a=W.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,C,d,b):0;c&&(v[c>>2]=b)},me:function(a,b,c,d){a=W.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},le:function(a,b,c,d){if(a=W.getShaderSource(Q[a]))b=0<b&&d?F(a,C,d,b):0,c&&(v[c>>2]=b)},oe:function(a,b,c){c?35716==b?(a=W.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=W.getShaderSource(Q[a]),v[c>>2]=a?a.length+
1:0):v[c>>2]=W.getShaderParameter(Q[a],b):U(1281)},ke:function(a){if(Gc[a])return Gc[a];switch(a){case 7939:var b=W.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Uc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=W.getParameter(a))||U(1280);b=Uc(b);break;case 7938:b=W.getParameter(7938);b=2<=V.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Uc(b);break;case 35724:b=W.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Uc(b);break;default:return U(1280),0}return Gc[a]=b},Cb:function(a,b){if(2>V.version)return U(1282),0;var c=Hc[a];if(c)return 0>b||b>=c.length?(U(1281),0):c[b];switch(a){case 7939:return c=W.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Uc(d)}),c=Hc[a]=c,0>b||b>=c.length?(U(1281),0):c[b];default:return U(1280),0}},mb:function(a,b,c,d,e){0>c?U(1281):e?(a=W.getSyncParameter(Ec[a],
b),v[d>>2]=a,null!==a&&d&&(v[d>>2]=1)):U(1281)},je:function(a,b,c){c?A[c>>2]=W.getTexParameter(a,b):U(1281)},ie:function(a,b,c){c?v[c>>2]=W.getTexParameter(a,b):U(1281)},Yb:function(a,b,c,d,e,f,k){a=O[a];if(a=W.getTransformFeedbackVarying(a,b))k&&0<c?(c=F(a.name,C,k,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0),e&&(v[e>>2]=a.size),f&&(v[f>>2]=a.type)},yb:function(a,b){return W.getUniformBlockIndex(O[a],E(b))},Ab:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))U(1281);else{a=O[a];for(var e=[],f=0;f<b;f++)e.push(E(v[c+
4*f>>2]));if(a=W.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)v[d+4*f>>2]=a[f]}else U(1281)},fe:function(a,b){b=E(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Fc[a]&&Fc[a].yg[b])&&0<=c&&c<a[0]?a[1]+c:-1},he:function(a,b,c){Vc(a,b,c,2)},ge:function(a,b,c){Vc(a,b,c,0)},Qb:function(a,b,c){Vc(a,b,c,0)},Wb:function(a,b,c){Wc(a,b,c,0)},Vb:function(a,b,c){Wc(a,b,c,0)},be:function(a,b,c){c?v[c>>2]=W.getVertexAttribOffset(a,
b):U(1281)},de:function(a,b,c){Wc(a,b,c,2)},ce:function(a,b,c){Wc(a,b,c,5)},ae:function(a,b){W.hint(a,b)},Pa:function(a,b,c){for(var d=Oc[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];W.invalidateFramebuffer(a,d)},Oa:function(a,b,c,d,e,f,k){for(var l=Oc[b],n=0;n<b;n++)l[n]=v[c+4*n>>2];W.invalidateSubFramebuffer(a,l,d,e,f,k)},$d:function(a){return(a=wc[a])?W.isBuffer(a):0},_d:function(a){return W.isEnabled(a)},Zd:function(a){return(a=xc[a])?W.isFramebuffer(a):0},Yd:function(a){return(a=O[a])?W.isProgram(a):0},vc:function(a){return(a=
Cc[a])?W.isQuery(a):0},ua:function(a){return(a=S[a])?W.rf.isQueryEXT(a):0},Xd:function(a){return(a=yc[a])?W.isRenderbuffer(a):0},gb:function(a){return(a=T[a])?W.isSampler(a):0},Wd:function(a){return(a=Q[a])?W.isShader(a):0},rb:function(a){return W.isSync(Ec[a])},Ud:function(a){return(a=zc[a])?W.isTexture(a):0},Va:function(a){return W.isTransformFeedback(Dc[a])},dc:function(a){return(a=Ac[a])?W.isVertexArray(a):0},ha:function(a){return(a=Ac[a])?W.isVertexArray(a):0},Td:function(a){W.lineWidth(a)},
Sd:function(a){W.linkProgram(O[a]);var b=O[a];a=Fc[a]={yg:{},cg:0,Bf:-1,Cf:-1};for(var c=a.yg,d=W.getProgramParameter(b,35718),e=0;e<d;++e){var f=W.getActiveUniform(b,e),k=f.name;a.cg=Math.max(a.cg,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var l=W.getUniformLocation(b,k);if(l){var n=Kc(P);c[k]=[f.size,n];P[n]=l;for(var t=1;t<f.size;++t)l=W.getUniformLocation(b,k+"["+t+"]"),n=Kc(P),P[n]=l}}},Ua:function(){W.pauseTransformFeedback()},Rd:function(a,b){3317==a&&(Ic=b);W.pixelStorei(a,
b)},Qd:function(a,b){W.polygonOffset(a,b)},Ra:function(){U(1280)},Qa:function(){U(1280)},ra:function(a,b){W.rf.queryCounterEXT(S[a],b)},Fc:function(a){W.readBuffer(a)},Pd:function(a,b,c,d,e,f,k){if(2<=V.version)if(W.Vf)W.readPixels(a,b,c,d,e,f,k);else{var l=Xc(f);W.readPixels(a,b,c,d,e,f,l,k>>Yc(l))}else(k=Zc(f,e,c,d,k))?W.readPixels(a,b,c,d,e,f,k):U(1280)},Od:function(){},Nd:function(a,b,c,d){W.renderbufferStorage(a,b,c,d)},ic:function(a,b,c,d,e){W.renderbufferStorageMultisample(a,b,c,d,e)},Ta:function(){W.resumeTransformFeedback()},
Md:function(a,b){W.sampleCoverage(a,!!b)},cb:function(a,b,c){W.samplerParameterf(T[a],b,c)},bb:function(a,b,c){W.samplerParameterf(T[a],b,A[c>>2])},eb:function(a,b,c){W.samplerParameteri(T[a],b,c)},db:function(a,b,c){W.samplerParameteri(T[a],b,v[c>>2])},Ld:function(a,b,c,d){W.scissor(a,b,c,d)},Jd:function(){U(1280)},Id:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?v[d+4*f>>2]:-1;e+=E(v[c+4*f>>2],0>k?void 0:k)}W.shaderSource(Q[a],e)},Hd:function(a,b,c){W.stencilFunc(a,b,c)},Gd:function(a,b,c,
d){W.stencilFuncSeparate(a,b,c,d)},Fd:function(a){W.stencilMask(a)},Ed:function(a,b){W.stencilMaskSeparate(a,b)},Dd:function(a,b,c){W.stencilOp(a,b,c)},Cd:function(a,b,c,d){W.stencilOpSeparate(a,b,c,d)},Bd:function(a,b,c,d,e,f,k,l,n){if(2<=V.version)if(W.sf)W.texImage2D(a,b,c,d,e,f,k,l,n);else if(n){var t=Xc(l);W.texImage2D(a,b,c,d,e,f,k,l,t,n>>Yc(t))}else W.texImage2D(a,b,c,d,e,f,k,l,null);else W.texImage2D(a,b,c,d,e,f,k,l,n?Zc(l,k,d,e,n):null)},Dc:function(a,b,c,d,e,f,k,l,n,t){if(W.sf)W.texImage3D(a,
b,c,d,e,f,k,l,n,t);else if(t){var r=Xc(n);W.texImage3D(a,b,c,d,e,f,k,l,n,r,t>>Yc(r))}else W.texImage3D(a,b,c,d,e,f,k,l,n,null)},Ad:function(a,b,c){W.texParameterf(a,b,c)},yd:function(a,b,c){W.texParameterf(a,b,A[c>>2])},xd:function(a,b,c){W.texParameteri(a,b,c)},wd:function(a,b,c){W.texParameteri(a,b,v[c>>2])},Na:function(a,b,c,d,e){W.texStorage2D(a,b,c,d,e)},Ma:function(a,b,c,d,e,f){W.texStorage3D(a,b,c,d,e,f)},vd:function(a,b,c,d,e,f,k,l,n){if(2<=V.version)if(W.sf)W.texSubImage2D(a,b,c,d,e,f,k,
l,n);else if(n){var t=Xc(l);W.texSubImage2D(a,b,c,d,e,f,k,l,t,n>>Yc(t))}else W.texSubImage2D(a,b,c,d,e,f,k,l,null);else t=null,n&&(t=Zc(l,k,e,f,n)),W.texSubImage2D(a,b,c,d,e,f,k,l,t)},Cc:function(a,b,c,d,e,f,k,l,n,t,r){if(W.sf)W.texSubImage3D(a,b,c,d,e,f,k,l,n,t,r);else if(r){var u=Xc(t);W.texSubImage3D(a,b,c,d,e,f,k,l,n,t,u,r>>Yc(u))}else W.texSubImage3D(a,b,c,d,e,f,k,l,n,t,null)},Zb:function(a,b,c,d){a=O[a];for(var e=[],f=0;f<b;f++)e.push(E(v[c+4*f>>2]));W.transformFeedbackVaryings(a,e,d)},ud:function(a,
b){W.uniform1f(P[a],b)},td:function(a,b,c){if(2<=V.version)W.uniform1fv(P[a],A,c>>2,b);else{if(288>=b)for(var d=$c[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);W.uniform1fv(P[a],d)}},sd:function(a,b){W.uniform1i(P[a],b)},rd:function(a,b,c){if(2<=V.version)W.uniform1iv(P[a],v,c>>2,b);else{if(288>=b)for(var d=ad[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);W.uniform1iv(P[a],d)}},Ob:function(a,b){W.uniform1ui(P[a],b)},Kb:function(a,b,c){W.uniform1uiv(P[a],
G,c>>2,b)},qd:function(a,b,c){W.uniform2f(P[a],b,c)},pd:function(a,b,c){if(2<=V.version)W.uniform2fv(P[a],A,c>>2,2*b);else{if(144>=b)for(var d=$c[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);W.uniform2fv(P[a],d)}},nd:function(a,b,c){W.uniform2i(P[a],b,c)},md:function(a,b,c){if(2<=V.version)W.uniform2iv(P[a],v,c>>2,2*b);else{if(144>=b)for(var d=ad[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);W.uniform2iv(P[a],
d)}},Nb:function(a,b,c){W.uniform2ui(P[a],b,c)},Jb:function(a,b,c){W.uniform2uiv(P[a],G,c>>2,2*b)},ld:function(a,b,c,d){W.uniform3f(P[a],b,c,d)},kd:function(a,b,c){if(2<=V.version)W.uniform3fv(P[a],A,c>>2,3*b);else{if(96>=b)for(var d=$c[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);W.uniform3fv(P[a],d)}},jd:function(a,b,c,d){W.uniform3i(P[a],b,c,d)},id:function(a,b,c){if(2<=V.version)W.uniform3iv(P[a],v,c>>2,3*b);else{if(96>=
b)for(var d=ad[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);W.uniform3iv(P[a],d)}},Mb:function(a,b,c,d){W.uniform3ui(P[a],b,c,d)},Ib:function(a,b,c){W.uniform3uiv(P[a],G,c>>2,3*b)},hd:function(a,b,c,d,e){W.uniform4f(P[a],b,c,d,e)},gd:function(a,b,c){if(2<=V.version)W.uniform4fv(P[a],A,c>>2,4*b);else{if(72>=b){var d=$c[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];d[f+3]=e[k+3]}}else d=
A.subarray(c>>2,c+16*b>>2);W.uniform4fv(P[a],d)}},fd:function(a,b,c,d,e){W.uniform4i(P[a],b,c,d,e)},ed:function(a,b,c){if(2<=V.version)W.uniform4iv(P[a],v,c>>2,4*b);else{if(72>=b)for(var d=ad[4*b-1],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);W.uniform4iv(P[a],d)}},Lb:function(a,b,c,d,e){W.uniform4ui(P[a],b,c,d,e)},Hb:function(a,b,c){W.uniform4uiv(P[a],G,c>>2,4*b)},vb:function(a,b,c){a=O[a];W.uniformBlockBinding(a,
b,c)},cd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix2fv(P[a],!!c,A,d>>2,4*b);else{if(72>=b)for(var e=$c[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);W.uniformMatrix2fv(P[a],!!c,e)}},pc:function(a,b,c,d){W.uniformMatrix2x3fv(P[a],!!c,A,d>>2,6*b)},nc:function(a,b,c,d){W.uniformMatrix2x4fv(P[a],!!c,A,d>>2,8*b)},bd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix3fv(P[a],!!c,A,d>>2,9*b);else{if(32>=
b)for(var e=$c[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);W.uniformMatrix3fv(P[a],!!c,e)}},oc:function(a,b,c,d){W.uniformMatrix3x2fv(P[a],!!c,A,d>>2,6*b)},lc:function(a,b,c,d){W.uniformMatrix3x4fv(P[a],!!c,A,d>>2,12*b)},ad:function(a,b,c,d){if(2<=V.version)W.uniformMatrix4fv(P[a],
!!c,A,d>>2,16*b);else{if(18>=b){var e=$c[16*b-1],f=A;d>>=2;for(var k=0;k<16*b;k+=16){var l=d+k;e[k]=f[l];e[k+1]=f[l+1];e[k+2]=f[l+2];e[k+3]=f[l+3];e[k+4]=f[l+4];e[k+5]=f[l+5];e[k+6]=f[l+6];e[k+7]=f[l+7];e[k+8]=f[l+8];e[k+9]=f[l+9];e[k+10]=f[l+10];e[k+11]=f[l+11];e[k+12]=f[l+12];e[k+13]=f[l+13];e[k+14]=f[l+14];e[k+15]=f[l+15]}}else e=A.subarray(d>>2,d+64*b>>2);W.uniformMatrix4fv(P[a],!!c,e)}},mc:function(a,b,c,d){W.uniformMatrix4x2fv(P[a],!!c,A,d>>2,8*b)},kc:function(a,b,c,d){W.uniformMatrix4x3fv(P[a],
!!c,A,d>>2,12*b)},$c:function(a){W.useProgram(O[a])},_c:function(a){W.validateProgram(O[a])},Zc:function(a,b){W.vertexAttrib1f(a,b)},Yc:function(a,b){W.vertexAttrib1f(a,A[b>>2])},Xc:function(a,b,c){W.vertexAttrib2f(a,b,c)},Wc:function(a,b){W.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},Vc:function(a,b,c,d){W.vertexAttrib3f(a,b,c,d)},Tc:function(a,b){W.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},Sc:function(a,b,c,d,e){W.vertexAttrib4f(a,b,c,d,e)},Rc:function(a,b){W.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+
8>>2],A[b+12>>2])},_a:function(a,b){W.vertexAttribDivisor(a,b)},ca:function(a,b){W.vertexAttribDivisor(a,b)},Nc:function(a,b){W.vertexAttribDivisor(a,b)},Oc:function(a,b){W.vertexAttribDivisor(a,b)},Ka:function(a,b){W.vertexAttribDivisor(a,b)},Ub:function(a,b,c,d,e){W.vertexAttribI4i(a,b,c,d,e)},Sb:function(a,b){W.vertexAttribI4i(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Tb:function(a,b,c,d,e){W.vertexAttribI4ui(a,b,c,d,e)},Rb:function(a,b){W.vertexAttribI4ui(a,G[b>>2],G[b+4>>2],G[b+8>>2],G[b+12>>
2])},Xb:function(a,b,c,d,e){W.vertexAttribIPointer(a,b,c,d,e)},Qc:function(a,b,c,d,e,f){W.vertexAttribPointer(a,b,c,!!d,e,f)},Pc:function(a,b,c,d){W.viewport(a,b,c,d)},ob:function(a,b,c,d){W.waitSync(Ec[a],b,(c>>>0)+4294967296*d)},f:function(){return 0},xa:function(a,b,c){C.copyWithin(a,b,b+c)},d:function(a){a>>>=0;var b=C.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{xa.grow(Math.min(2147483648,
d)-Ha.byteLength+65535>>>16);Ja();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Aa:function(a,b,c,d,e){a=H.get(a);Od(a,b,c,d,e)},e:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Da:function(a){for(var b=rc();rc()-b<a;);},Ba:function(a,b){try{var c=0;Qd().forEach(function(d,e){var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++>>0]=d.charCodeAt(f);q[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==
typeof N&&d instanceof K||p(d),d.mf}},Ca:function(a,b){try{var c=Qd();v[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});v[b>>2]=d;return 0}catch(e){return"undefined"!==typeof N&&e instanceof K||p(e),e.mf}},j:function(a){Ae(a)},o:function(a){try{var b=qc(a);Xb(b);return 0}catch(c){return"undefined"!==typeof N&&c instanceof K||p(c),c.mf}},za:function(a,b){try{var c=qc(a);q[b>>0]=c.tty?2:M(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof N&&d instanceof K||
p(d),d.mf}},hb:function(a,b,c,d){try{a:{for(var e=qc(a),f=a=0;f<c;f++){var k=v[b+(8*f+4)>>2],l=e,n=v[b+8*f>>2],t=k,r=void 0,u=q;if(0>t||0>r)throw new K(28);if(null===l.fd)throw new K(8);if(1===(l.flags&2097155))throw new K(8);if(M(l.node.mode))throw new K(31);if(!l.jf.read)throw new K(28);var w="undefined"!==typeof r;if(!w)r=l.position;else if(!l.seekable)throw new K(70);var y=l.jf.read(l,u,n,t,r);w||(l.position+=y);var B=y;if(0>B){var D=-1;break a}a+=B;if(B<k)break}D=a}v[d>>2]=D;return 0}catch(I){return"undefined"!==
typeof N&&I instanceof K||p(I),I.mf}},Ia:function(a,b,c,d,e){try{var f=qc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Yb(f,a,d);x=[f.position>>>0,(z=f.position,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];v[e>>2]=x[0];v[e+4>>2]=x[1];f.$f&&0===a&&0===d&&(f.$f=null);return 0}catch(k){return"undefined"!==typeof N&&k instanceof K||p(k),k.mf}},p:function(a,b,c,d){try{a:{for(var e=qc(a),f=
a=0;f<c;f++){var k=Zb(e,q,v[b+8*f>>2],v[b+(8*f+4)>>2],void 0);if(0>k){var l=-1;break a}a+=k}l=a}v[d>>2]=l;return 0}catch(n){return"undefined"!==typeof N&&n instanceof K||p(n),n.mf}},k:function(a){var b=Date.now();v[a>>2]=b/1E3|0;v[a+4>>2]=b%1E3*1E3|0;return 0},Ke:function(a,b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?Ad():Md(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<Td[139265];e==
X.length&&(d?g.xf=wd(g.canvas,!0,!0,{antialias:1<Td[135181],depth:0<Td[135173],stencil:0<Td[135174],alpha:0<Td[135172]}):kc());!g.xf&&d?f=0:(a=new Sd(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id)}return f},A:function(){Td=Wd},Jc:function(a){a:{if(a=Ud(a)){a.zg&&H.get(a.zg)(a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}g.xf=void 0}a=void 0}return a},dd:function(a,b,c){ua(b,Gd,"double");ua(c,Hd,"double")},Uc:function(a,b,c){var d=0,e=0;if(a=
Ud(a))d=a.width,e=a.height;b&&ua(b,d,"i32");c&&ua(c,e,"i32")},a:function(a){return Be(a)},L:function(){if(X)return 1;rc();Td=Wd;X=[];Y=null;window.addEventListener("gamepadconnected",ae,!0);window.addEventListener("gamepaddisconnected",ce,!0);window.addEventListener("keydown",de,!0);window.addEventListener("keypress",Zd,!0);window.addEventListener("keyup",ee,!0);window.addEventListener("blur",fe,!0);g.canvas.addEventListener("touchmove",ge,!0);g.canvas.addEventListener("touchstart",ke,!0);g.canvas.addEventListener("touchcancel",
le,!0);g.canvas.addEventListener("touchend",le,!0);g.canvas.addEventListener("mousemove",ge,!0);g.canvas.addEventListener("mousedown",ke,!0);g.canvas.addEventListener("mouseup",le,!0);g.canvas.addEventListener("wheel",me,!0);g.canvas.addEventListener("mousewheel",me,!0);g.canvas.addEventListener("mouseenter",he,!0);g.canvas.addEventListener("mouseleave",ie,!0);g.canvas.addEventListener("drop",se,!0);g.canvas.addEventListener("dragover",te,!0);Ld.push(function(a,b){if(Y){var c=!0;document.fullscreen||
document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.wg=Y.x,Y.xg=Y.y,Y.vg=Y.width,Y.ug=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Zf=!0):1==Y.Zf?(Y.x=Y.wg,Y.y=Y.xg,Y.width=Y.vg,Y.height=Y.ug,Y.Zf=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(Md(Y.width,Y.height,!0),Y&&Y.Ag&&H.get(Y.Ag)(Y.id,Y.width,Y.height),Y&&Y.Jf&&H.get(Y.Jf)(Y.id,Y.width,Y.height))}});return 1},ze:function(){},qa:function(){},Vd:function(a,b){if(a=Ud(a)){var c=a.Hf;a.Hf=
b;b=c}else b=null;return b},W:function(a){var b=Vd;Vd=a;return b},ee:function(a,b){a=Ud(a);if(!a)return null;var c=a.Jf;a.Jf=b;return c},Kd:function(a,b){if(a=Ud(a)){var c=a.Kf;a.Kf=b;b=c}else b=null;return b},od:function(a,b){if(a=Ud(a)){var c=a.Of;a.Of=b;b=c}else b=null;return b},zd:function(a,b){if(a=Ud(a)){var c=a.Qf;a.Qf=b;b=c}else b=null;return b},fa:function(){},yc:function(){window.removeEventListener("gamepadconnected",ae,!0);window.removeEventListener("gamepaddisconnected",ce,!0);window.removeEventListener("keydown",
de,!0);window.removeEventListener("keypress",Zd,!0);window.removeEventListener("keyup",ee,!0);window.removeEventListener("blur",fe,!0);g.canvas.removeEventListener("touchmove",ge,!0);g.canvas.removeEventListener("touchstart",ke,!0);g.canvas.removeEventListener("touchcancel",le,!0);g.canvas.removeEventListener("touchend",le,!0);g.canvas.removeEventListener("mousemove",ge,!0);g.canvas.removeEventListener("mousedown",ke,!0);g.canvas.removeEventListener("mouseup",le,!0);g.canvas.removeEventListener("wheel",
me,!0);g.canvas.removeEventListener("mousewheel",me,!0);g.canvas.removeEventListener("mouseenter",he,!0);g.canvas.removeEventListener("mouseleave",ie,!0);g.canvas.removeEventListener("drop",se,!0);g.canvas.removeEventListener("dragover",te,!0);g.canvas.width=g.canvas.height=1;Y=X=null},h:function(a,b){Td[a]=b},m:function(){},g:function(){return 0}};
(function(){function a(e){g.asm=e.exports;xa=g.asm.Ve;Ja();H=g.asm.We;Ua("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return $a().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){h("failed to asynchronously prepare wasm: "+f);p(f)})}var d={a:Ce};Ta("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return h("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ta||"function"!==typeof WebAssembly.instantiateStreaming||
Xa()||Va("file://")||"function"!==typeof fetch?c(b):fetch(Wa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){h("wasm streaming compile failed: "+f);h("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Oa=g.___wasm_call_ctors=function(){return(Oa=g.___wasm_call_ctors=g.asm.Xe).apply(null,arguments)},re=g._free=function(){return(re=g._free=g.asm.Ye).apply(null,arguments)},Aa=g._malloc=function(){return(Aa=g._malloc=g.asm.Ze).apply(null,arguments)},xe=g.___errno_location=function(){return(xe=g.___errno_location=g.asm._e).apply(null,arguments)};g._main=function(){return(g._main=g.asm.$e).apply(null,arguments)};
var Be=g._emscripten_GetProcAddress=function(){return(Be=g._emscripten_GetProcAddress=g.asm.af).apply(null,arguments)},ze=g._memset=function(){return(ze=g._memset=g.asm.bf).apply(null,arguments)},Fa=g.stackAlloc=function(){return(Fa=g.stackAlloc=g.asm.cf).apply(null,arguments)},ye=g._memalign=function(){return(ye=g._memalign=g.asm.df).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.ef).apply(null,arguments)};
g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.ff).apply(null,arguments)};g.addRunDependency=Ta;g.removeRunDependency=Ua;g.FS_createPath=cc;g.FS_createDataFile=ec;g.FS_createPreloadedFile=jc;g.FS_createLazyFile=ic;g.FS_createDevice=fc;g.FS_unlink=Tb;var De;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Sa=function Ee(){De||Fe();De||(Sa=Ee)};
function Fe(a){function b(){if(!De&&(De=!0,g.calledRun=!0,!ya)){g.noFSInit||ac||(ac=!0,$b(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?fc("/dev","stdin",g.stdin):Sb("/dev/tty","/dev/stdin"),g.stdout?fc("/dev","stdout",null,g.stdout):Sb("/dev/tty","/dev/stdout"),g.stderr?fc("/dev","stderr",null,g.stderr):Sb("/dev/tty1","/dev/stderr"),Vb("/dev/stdin",0),Vb("/dev/stdout",1),Vb("/dev/stderr",1));db(La);Ab=!1;db(Ma);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ge){var c=a,d=g._main;
c=c||[];var e=c.length+1,f=Fa(4*(e+1));v[f>>2]=Ea(da);for(var k=1;k<e;k++)v[(f>>2)+k]=Ea(c[k-1]);v[(f>>2)+e]=0;try{var l=d(e,f);Ae(l,!0)}catch(n){n instanceof pa||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),h("exception thrown: "+c),ea(1,n)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Na.unshift(c);db(Na)}}a=a||ca;if(!(0<Qa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Pa();
db(Ka);0<Qa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Fe;function Ae(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);ya=!0}ea(a,new pa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ge=!0;g.noInitialRun&&(Ge=!1);noExitRuntime=!0;Fe();
