
var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.Vf||(g.Vf=0);g.Vf++;
(function(a){function b(m,t,r){var u=new XMLHttpRequest;u.open("GET",m,!0);u.responseType="arraybuffer";u.onprogress=function(w){var y=t;w.total&&(y=w.total);if(w.loaded){u.kf?g.vf[m].loaded=w.loaded:(u.kf=!0,g.vf||(g.vf={}),g.vf[m]={loaded:w.loaded,total:y});var B=y=w=0,D;for(D in g.vf){var H=g.vf[D];w+=H.total;y+=H.loaded;B++}w=Math.ceil(w*g.Vf/B);g.setStatus&&g.setStatus("Downloading data... ("+y+"/"+w+")")}else!g.vf&&g.setStatus&&g.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+
m);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)r(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}function c(m){console.error("package error:",m)}function d(){function m(w,y,B){this.start=w;this.Uf=y;this.audio=B}function t(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);m.prototype.Eg=w;w=a.files;for(var y=0;y<
w.length;++y)m.prototype.kf[w[y].filename].onload();g.removeRunDependency("datafile_build/web/index.data")}g.FS_createPath("/","assets",!0,!0);m.prototype={kf:{},open:function(w,y){this.name=y;this.kf[y]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Dg(this.Eg.subarray(this.start,this.Uf))},Dg:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.kf[this.name]=null}};for(var r=a.files,u=0;u<r.length;++u)(new m(r[u].start,
r[u].end,r[u].audio)).open("GET",r[u].filename);g.addRunDependency("datafile_build/web/index.data");g.qg||(g.qg={});g.qg["build/web/index.data"]={$g:!1};l?(t(l),l=null):k=t}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,h("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,k=null,l=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){k?(k(m),k=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/assets/atlas.dat",
start:0,end:95,audio:0},{filename:"/assets/atlas.png",start:95,end:4118,audio:0}],remote_package_size:4118,package_uuid:"2ffbfc9a-0674-4b88-afda-9055cf1bef96"});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;
var n="",ka,la,ma,na,oa;
if(ia)n=ha?require("path").dirname(n)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",
p),ea=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?n=self.location.href:"undefined"!==typeof document&&document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=g.print||console.log.bind(console),h=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);function ra(a){sa||(sa={});sa[a]||(sa[a]=1,h(a))}var sa,ta;g.wasmBinary&&(ta=g.wasmBinary);
var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&p("no native wasm support detected");
function ua(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":va[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":wa=[b>>>0,(x=b,1<=+Math.abs(x)?0<x?(Math.min(+Math.floor(x/4294967296),4294967295)|0)>>>0:~~+Math.ceil((x-+(~~x>>>0))/4294967296)>>>0:0)];v[a>>2]=wa[0];v[a+4>>2]=wa[1];break;case "float":z[a>>2]=b;break;case "double":xa[a>>3]=b;break;default:p("invalid type for setValue: "+c)}}var ya,za=!1;
function assert(a,b){a||p("Assertion failed: "+b)}function Aa(a){var b=Ba(a.length);a.subarray||a.slice?A.set(a,b):A.set(new Uint8Array(a),b);return b}var Ca="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Da(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?Da(A,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Fa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ga(a){var b=Fa(a)+1,c=Ha(b);E(a,q,c,b);return c}var Ia,q,A,va,Ja,v,F,z,xa;
function Ka(){var a=ya.buffer;Ia=a;g.HEAP8=q=new Int8Array(a);g.HEAP16=va=new Int16Array(a);g.HEAP32=v=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=Ja=new Uint16Array(a);g.HEAPU32=F=new Uint32Array(a);g.HEAPF32=z=new Float32Array(a);g.HEAPF64=xa=new Float64Array(a)}var G,La=[],Ma=[],Na=[],Oa=[];Ma.push({jg:function(){Pa()}});function Qa(){var a=g.preRun.shift();La.unshift(a)}var Ra=0,Sa=null,Ta=null;function Ua(){Ra++;g.monitorRunDependencies&&g.monitorRunDependencies(Ra)}
function Va(){Ra--;g.monitorRunDependencies&&g.monitorRunDependencies(Ra);if(0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}g.preloadedImages={};g.preloadedAudios={};function p(a){if(g.onAbort)g.onAbort(a);h(a);za=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Wa(a){var b=Xa;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ya(){return Wa("data:application/octet-stream;base64,")}
var Xa="index.wasm";if(!Ya()){var Za=Xa;Xa=g.locateFile?g.locateFile(Za,n):n+Za}function $a(){var a=Xa;try{if(a==Xa&&ta)return new Uint8Array(ta);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function ab(){if(!ta&&(fa||ha)){if("function"===typeof fetch&&!Wa("file://"))return fetch(Xa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Xa+"'";return a.arrayBuffer()}).catch(function(){return $a()});if(la)return new Promise(function(a,b){la(Xa,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return $a()})}
var x,wa,cb={10359:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},10525:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},10751:function(a){var b=g.SDL2;if(a){void 0!==b.capture.Bf&&clearTimeout(b.capture.Bf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.jf&&(b.capture.jf.onaudioprocess=function(){},b.capture.jf.disconnect(),b.capture.jf=void 0);void 0!==b.capture.Hf&&(b.capture.Hf.disconnect(),b.capture.Hf=void 0);void 0!==b.capture.Nf&&(b.capture.Nf=void 0);b.capture=void 0}else void 0!=b.audio.jf&&(b.audio.jf.disconnect(),b.audio.jf=void 0),b.audio=void 0;void 0!==b.hf&&void 0===b.audio&&void 0===b.capture&&(b.hf.close(),b.hf=void 0)},11923:function(a){"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;
a?b.capture={}:b.audio={};b.hf||("undefined"!==typeof AudioContext?b.hf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.hf=new webkitAudioContext),b.hf&&bb(b.hf));return void 0===b.hf?-1:0},12476:function(){return g.SDL2.hf.sampleRate},12546:function(a,b,c,d){function e(){}function f(l){void 0!==k.capture.Bf&&(clearTimeout(k.capture.Bf),k.capture.Bf=void 0);k.capture.Hf=k.hf.createMediaStreamSource(l);k.capture.jf=k.hf.createScriptProcessor(b,a,1);k.capture.jf.onaudioprocess=function(m){void 0!==
k&&void 0!==k.capture&&(m.outputBuffer.getChannelData(0).fill(0),k.capture.Qf=m.inputBuffer,m=[d],G.get(c).apply(null,m))};k.capture.Hf.connect(k.capture.jf);k.capture.jf.connect(k.hf.destination);k.capture.stream=l}var k=g.SDL2;k.capture.Nf=k.hf.createBuffer(a,b,k.hf.sampleRate);k.capture.Nf.getChannelData(0).fill(0);k.capture.Bf=setTimeout(function(){k.capture.Qf=k.capture.Nf;var l=[d];G.get(c).apply(null,l)},b/k.hf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},14198:function(a,b,c,d){var e=g.SDL2;e.audio.jf=e.hf.createScriptProcessor(b,0,a);e.audio.jf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.gg=f.outputBuffer,f=[d],G.get(c).apply(null,f))};e.audio.jf.connect(e.hf.destination)},14608:function(a,b){for(var c=g.SDL2,d=c.audio.gg.numberOfChannels,e=0;e<d;++e){var f=c.audio.gg.getChannelData(e);
if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var k=0;k<b;++k)f[k]=z[a+(k*d+e<<2)>>2]}},15088:function(a,b){for(var c=g.SDL2,d=c.capture.Qf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Qf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var k=0;k<b;++k)ua(a+4*k,f[k],"float");else for(k=0;k<b;++k)ua(a+
4*(k*d+e),f[k],"float")}}};function db(a,b,c){a.addEventListener(b,c,{once:!0})}function bb(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&db(d,c,function(){"suspended"===a.state&&a.resume()})})})}function fb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.jg;"number"===typeof c?void 0===b.Cf?G.get(c)():G.get(c)(b.Cf):c(void 0===b.Cf?null:b.Cf)}}}
function gb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function hb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ib(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function jb(a){if("/"===a)return"/";a=hb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function kb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){p("randomDevice")}}
function lb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var mb=[];function nb(a,b){mb[a]={input:[],output:[],xf:b};ob(a,pb)}
var pb={open:function(a){var b=mb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.xf.flush(a.tty)},flush:function(a){a.tty.xf.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.xf.kg)throw new I(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.xf.kg(a.tty)}catch(l){throw new I(29);}if(void 0===k&&0===e)throw new I(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.xf.ag)throw new I(60);
try{for(var e=0;e<d;e++)a.tty.xf.ag(a.tty,b[c+e])}catch(f){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},rb={kg:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.kf?Buffer.kf(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=qb(b,!0)}return a.input.shift()},ag:function(a,b){null===b||10===b?(qa(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Da(a.output,0)),a.output=[])}},sb={ag:function(a,b){null===b||10===b?(h(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Da(a.output,0)),a.output=[])}},J={qf:null,rf:function(){return J.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.qf||(J.qf={dir:{node:{sf:J.ff.sf,mf:J.ff.mf,lookup:J.ff.lookup,If:J.ff.If,rename:J.ff.rename,unlink:J.ff.unlink,rmdir:J.ff.rmdir,readdir:J.ff.readdir,symlink:J.ff.symlink},stream:{tf:J.ef.tf}},file:{node:{sf:J.ff.sf,mf:J.ff.mf},stream:{tf:J.ef.tf,read:J.ef.read,write:J.ef.write,cg:J.ef.cg,Jf:J.ef.Jf,Lf:J.ef.Lf}},link:{node:{sf:J.ff.sf,mf:J.ff.mf,readlink:J.ff.readlink},stream:{}},fg:{node:{sf:J.ff.sf,
mf:J.ff.mf},stream:tb}});c=ub(a,b,c,d);16384===(c.mode&61440)?(c.ff=J.qf.dir.node,c.ef=J.qf.dir.stream,c.df={}):32768===(c.mode&61440)?(c.ff=J.qf.file.node,c.ef=J.qf.file.stream,c.gf=0,c.df=null):40960===(c.mode&61440)?(c.ff=J.qf.link.node,c.ef=J.qf.link.stream):8192===(c.mode&61440)&&(c.ff=J.qf.fg.node,c.ef=J.qf.fg.stream);c.timestamp=Date.now();a&&(a.df[b]=c,a.timestamp=c.timestamp);return c},ah:function(a){if(a.df&&a.df.subarray){for(var b=[],c=0;c<a.gf;++c)b.push(a.df[c]);return b}return a.df},
bh:function(a){return a.df?a.df.subarray?a.df.subarray(0,a.gf):new Uint8Array(a.df):new Uint8Array(0)},hg:function(a,b){var c=a.df?a.df.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.df,a.df=new Uint8Array(b),0<a.gf&&a.df.set(c.subarray(0,a.gf),0))},Qg:function(a,b){if(a.gf!=b)if(0==b)a.df=null,a.gf=0;else{if(!a.df||a.df.subarray){var c=a.df;a.df=new Uint8Array(b);c&&a.df.set(c.subarray(0,Math.min(b,a.gf)))}else if(a.df||(a.df=[]),a.df.length>b)a.df.length=b;
else for(;a.df.length<b;)a.df.push(0);a.gf=b}},ff:{sf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.gf:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ag=4096;b.blocks=Math.ceil(b.size/b.Ag);return b},mf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&
(a.timestamp=b.timestamp);void 0!==b.size&&J.Qg(a,b.size)},lookup:function(){throw vb[44];},If:function(a,b,c,d){return J.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=wb(b,c)}catch(f){}if(d)for(var e in d.df)throw new I(55);}delete a.parent.df[a.name];a.parent.timestamp=Date.now();a.name=c;b.df[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.df[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=wb(a,b),d;for(d in c.df)throw new I(55);
delete a.df[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.df)a.df.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},ef:{read:function(a,b,c,d,e){var f=a.node.df;if(e>=a.node.gf)return 0;a=Math.min(a.node.gf-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===
q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.df||a.df.subarray)){if(f)return a.df=b.subarray(c,c+d),a.gf=d;if(0===a.gf&&0===e)return a.df=b.slice(c,c+d),a.gf=d;if(e+d<=a.gf)return a.df.set(b.subarray(c,c+d),e),d}J.hg(a,e+d);if(a.df.subarray&&b.subarray)a.df.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.df[e+f]=b[c+f];a.gf=Math.max(a.gf,e+d);return d},tf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.gf);if(0>b)throw new I(28);
return b},cg:function(a,b,c){J.hg(a.node,b+c);a.node.gf=Math.max(a.node.gf,b+c)},Jf:function(a,b,c,d,e,f){if(0!==b)throw new I(28);if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.df;if(f&2||a.buffer!==Ia){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=Ba(f);c<f;)q[b+c++]=0;c=b;if(!c)throw new I(48);q.set(a,c)}else d=!1,c=a.byteOffset;return{Og:c,Pf:d}},Lf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);
if(e&2)return 0;J.ef.write(a,b,0,d,c,!1);return 0}}},xb=null,yb={},zb=[],Ab=1,Bb=null,Cb=!0,Db={},I=null,vb={};
function Eb(a,b){a=lb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ig:!0,bg:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.bg)throw new I(32);a=gb(a.split("/").filter(function(k){return!!k}),!1);var e=xb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=wb(e,a[d]);c=hb(c+"/"+a[d]);e.Af&&(!f||f&&b.ig)&&(e=e.Af.root);if(!f||b.Wf)for(f=0;40960===(e.mode&61440);)if(e=Fb(c),c=lb(ib(c),e),e=Eb(c,{bg:b.bg}).node,40<f++)throw new I(32);}return{path:c,node:e}}
function Gb(a){for(var b;;){if(a===a.parent)return a=a.rf.og,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Hb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Bb.length}function wb(a,b){var c;if(c=(c=Ib(a,"x"))?c:a.ff.lookup?0:2)throw new I(c,a);for(c=Bb[Hb(a.id,b)];c;c=c.wf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ff.lookup(a,b)}
function ub(a,b,c,d){a=new Jb(a,b,c,d);b=Hb(a.parent.id,a.name);a.wf=Bb[b];return Bb[b]=a}var Kb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Lb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ib(a,b){if(Cb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Mb(a,b){try{return wb(a,b),20}catch(c){}return Ib(a,"wx")}
function Nb(a){var b=4096;for(a=a||0;a<=b;a++)if(!zb[a])return a;throw new I(33);}function Ob(a,b){Pb||(Pb=function(){},Pb.prototype={});var c=new Pb,d;for(d in a)c[d]=a[d];a=c;b=Nb(b);a.fd=b;return zb[b]=a}var tb={open:function(a){a.ef=yb[a.node.rdev].ef;a.ef.open&&a.ef.open(a)},tf:function(){throw new I(70);}};function ob(a,b){yb[a]={ef:b}}
function Qb(a,b){var c="/"===b,d=!b;if(c&&xb)throw new I(10);if(!c&&!d){var e=Eb(b,{ig:!1});b=e.path;e=e.node;if(e.Af)throw new I(10);if(16384!==(e.mode&61440))throw new I(54);}b={type:a,jh:{},og:b,Mg:[]};a=a.rf(b);a.rf=b;b.root=a;c?xb=a:e&&(e.Af=b,e.rf&&e.rf.Mg.push(b))}function Rb(a,b,c){var d=Eb(a,{parent:!0}).node;a=jb(a);if(!a||"."===a||".."===a)throw new I(28);var e=Mb(d,a);if(e)throw new I(e);if(!d.ff.If)throw new I(63);return d.ff.If(d,a,b,c)}function K(a){return Rb(a,16895,0)}
function Sb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Rb(a,b|8192,c)}function Tb(a,b){if(!lb(a))throw new I(44);var c=Eb(b,{parent:!0}).node;if(!c)throw new I(44);b=jb(b);var d=Mb(c,b);if(d)throw new I(d);if(!c.ff.symlink)throw new I(63);c.ff.symlink(c,b,a)}
function Ub(a){var b=Eb(a,{parent:!0}).node,c=jb(a),d=wb(b,c);a:{try{var e=wb(b,c)}catch(k){e=k.lf;break a}var f=Ib(b,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new I(e);if(!b.ff.unlink)throw new I(63);if(d.Af)throw new I(10);try{Db.willDeletePath&&Db.willDeletePath(a)}catch(k){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.ff.unlink(b,c);b=Hb(d.parent.id,d.name);if(Bb[b]===d)Bb[b]=d.wf;else for(b=Bb[b];b;){if(b.wf===d){b.wf=d.wf;break}b=b.wf}try{if(Db.onDeletePath)Db.onDeletePath(a)}catch(k){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Fb(a){a=Eb(a).node;if(!a)throw new I(44);if(!a.ff.readlink)throw new I(28);return lb(Gb(a.parent),a.ff.readlink(a))}function Vb(a,b){var c;"string"===typeof a?c=Eb(a,{Wf:!0}).node:c=a;if(!c.ff.mf)throw new I(63);c.ff.mf(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Wb(a,b,c,d){if(""===a)throw new I(44);if("string"===typeof b){var e=Kb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=hb(a);try{f=Eb(a,{Wf:!(b&131072)}).node}catch(l){}}e=!1;if(b&64)if(f){if(b&128)throw new I(20);}else f=Rb(a,c,0),e=!0;if(!f)throw new I(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new I(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Lb(b)||b&512)?31:Ib(f,Lb(b)):44))throw new I(c);if(b&512){c=f;var k;"string"===typeof c?k=Eb(c,{Wf:!0}).node:k=c;if(!k.ff.mf)throw new I(63);if(16384===(k.mode&61440))throw new I(31);if(32768!==(k.mode&61440))throw new I(28);if(c=Ib(k,"w"))throw new I(c);k.ff.mf(k,{size:0,timestamp:Date.now()})}b&=-131713;d=Ob({node:f,path:Gb(f),flags:b,seekable:!0,position:0,ef:f.ef,Sg:[],error:!1},d);d.ef.open&&d.ef.open(d);!g.logReadFiles||b&1||(Xb||(Xb={}),a in Xb||(Xb[a]=1,h("FS.trackingDelegate error on read file: "+
a)));try{Db.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Db.onOpenFile(a,f))}catch(l){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function Yb(a){if(null===a.fd)throw new I(8);a.Yf&&(a.Yf=null);try{a.ef.close&&a.ef.close(a)}catch(b){throw b;}finally{zb[a.fd]=null}a.fd=null}
function Zb(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.ef.tf)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.ef.tf(a,b,c);a.Sg=[]}
function $b(a,b,c,d,e,f){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(16384===(a.node.mode&61440))throw new I(31);if(!a.ef.write)throw new I(28);a.seekable&&a.flags&1024&&Zb(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new I(70);b=a.ef.write(a,b,c,d,e,f);k||(a.position+=b);try{if(a.path&&Db.onWriteToFile)Db.onWriteToFile(a.path)}catch(l){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
l.message)}return b}function ac(){I||(I=function(a,b){this.node=b;this.Rg=function(c){this.lf=c};this.Rg(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(function(a){vb[a]=new I(a);vb[a].stack="<generic error, no stack>"}))}var bc;function cc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function dc(a,b){a="string"===typeof a?a:Gb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=hb(a+"/"+c);try{K(d)}catch(e){}a=d}}return d}
function ec(a,b,c,d){a=hb(("string"===typeof a?a:Gb(a))+"/"+b);c=cc(c,d);return Rb(a,(void 0!==c?c:438)&4095|32768,0)}function fc(a,b,c,d,e,f){a=b?hb(("string"===typeof a?a:Gb(a))+"/"+b):a;d=cc(d,e);e=Rb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Vb(e,d|146);a=Wb(e,577);$b(a,c,0,c.length,0,f);Yb(a);Vb(e,d)}return e}
function L(a,b,c,d){a=hb(("string"===typeof a?a:Gb(a))+"/"+b);b=cc(!!c,!!d);L.mg||(L.mg=64);var e=L.mg++<<8|0;ob(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,k,l,m){for(var t=0,r=0;r<m;r++){try{var u=c()}catch(w){throw new I(29);}if(void 0===u&&0===t)throw new I(6);if(null===u||void 0===u)break;t++;k[l+r]=u}t&&(f.node.timestamp=Date.now());return t},write:function(f,k,l,m){for(var t=0;t<m;t++)try{d(k[l+t])}catch(r){throw new I(29);}m&&(f.node.timestamp=
Date.now());return t}});return Sb(a,b,e)}function hc(a){if(!(a.Ig||a.Jg||a.link||a.df)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.df=qb(ka(a.url),!0),a.gf=a.df.length}catch(b){throw new I(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function ic(a,b,c,d,e){function f(){this.Zf=!1;this.kf=[]}f.prototype.get=function(r){if(!(r>this.length-1||0>r)){var u=r%this.chunkSize;return this.lg(r/this.chunkSize|0)[u]}};f.prototype.Uf=function(r){this.lg=r};f.prototype.dg=function(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var u=Number(r.getResponseHeader("Content-length")),w,y=(w=r.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;r=(w=r.getResponseHeader("Content-Encoding"))&&"gzip"===w;var B=1048576;y||(B=u);var D=this;D.Uf(function(H){var eb=H*B,Ea=(H+1)*B-1;Ea=Math.min(Ea,u-1);if("undefined"===typeof D.kf[H]){var ne=D.kf;if(eb>Ea)throw Error("invalid range ("+eb+", "+Ea+") or no bytes requested!");if(Ea>u-1)throw Error("only "+u+" bytes available! programmer error!");var O=new XMLHttpRequest;O.open("GET",c,!1);u!==B&&O.setRequestHeader("Range","bytes="+eb+"-"+Ea);"undefined"!=typeof Uint8Array&&(O.responseType=
"arraybuffer");O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);if(!(200<=O.status&&300>O.status||304===O.status))throw Error("Couldn't load "+c+". Status: "+O.status);eb=void 0!==O.response?new Uint8Array(O.response||[]):qb(O.responseText||"",!0);ne[H]=eb}if("undefined"===typeof D.kf[H])throw Error("doXHR failed!");return D.kf[H]});if(r||!u)B=u=1,B=u=this.lg(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.zg=
u;this.yg=B;this.Zf=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.Zf||this.dg();return this.zg}},chunkSize:{get:function(){this.Zf||this.dg();return this.yg}}});var l=void 0}else l=c,k=void 0;var m=ec(a,b,d,e);k?m.df=k:l&&(m.df=null,m.url=l);Object.defineProperties(m,{gf:{get:function(){return this.df.length}}});
var t={};Object.keys(m.ef).forEach(function(r){var u=m.ef[r];t[r]=function(){hc(m);return u.apply(null,arguments)}});t.read=function(r,u,w,y,B){hc(m);r=r.node.df;if(B>=r.length)return 0;y=Math.min(r.length-B,y);if(r.slice)for(var D=0;D<y;D++)u[w+D]=r[B+D];else for(D=0;D<y;D++)u[w+D]=r.get(B+D);return y};m.ef=t;return m}
function jc(a,b,c,d,e,f,k,l,m,t){function r(y){function B(H){t&&t();l||fc(a,b,H,d,e,m);f&&f();Va(w)}var D=!1;g.preloadPlugins.forEach(function(H){!D&&H.canHandle(u)&&(H.handle(y,u,B,function(){k&&k();Va(w)}),D=!0)});D||B(y)}kc();var u=b?lb(hb(a+"/"+b)):a,w="cp "+u;Ua(w);"string"==typeof c?lc(c,function(y){r(y)},k):r(c)}var M={},Pb,Xb,mc={},nc=void 0;function oc(){nc+=4;return v[nc-4>>2]}function pc(a){a=zb[a];if(!a)throw new I(8);return a}var qc;
ia?qc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?qc=dateNow:qc=function(){return performance.now()};function rc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,k){b.drawElementsInstancedANGLE(c,d,e,f,k)})}
function sc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function tc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var uc=1,vc=[],N=[],wc=[],xc=[],yc=[],P=[],Q=[],R=[],zc=[],S=[],Ac=[],T=[],Bc=[],Cc=[],Dc={},Ec={},Fc={},Gc=4;function U(a){Hc||(Hc=a)}function Ic(a){for(var b=uc++,c=a.length;c<b;c++)a[c]=null;return b}function Jc(a,b){if(a=1<b.ng?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=Ic(zc),d={dh:c,attributes:b,version:b.ng,Of:a};a.canvas&&(a.canvas.Ug=d);zc[c]=d;("undefined"===typeof b.Cg||b.Cg)&&Kc(d);b=c}else b=0;return b}
function Kc(a){a||(a=V);if(!a.Gg){a.Gg=!0;var b=a.Of;rc(b);sc(b);tc(b);b.Yg=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.eh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.nf=b.getExtension("EXT_disjoint_timer_query");b.hh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var Lc={},Hc,V,Mc=[];
function Nc(a,b,c,d){for(var e=0;e<a;e++){var f=W[c](),k=f&&Ic(d);f?(f.name=k,d[k]=f):U(1282);v[b+4*e>>2]=k}}function Oc(a,b,c,d,e,f,k,l){b=N[b];if(a=W[a](b,c))d=l&&E(a.name,A,l,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),k&&(v[k>>2]=a.type)}function Pc(a,b){F[a>>2]=b;F[a+4>>2]=(b-F[a>>2])/4294967296}
function Qc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=W.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>V.version){U(1282);return}d=2*(W.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>V.version){U(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=W.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){U(1280);
h("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:U(1280);h("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Pc(b,d);break;case 0:v[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else U(1281)}
function Rc(a,b,c,d){if(c){b=W.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:U(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{U(1280);return}break;default:U(1280);return}switch(d){case 1:Pc(c,a);break;case 0:v[c>>2]=a;break;case 2:z[c>>2]=a;break;case 4:q[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else U(1281)}
function Sc(a){var b=Fa(a)+1,c=Ba(b);E(a,A,c,b);return c}function Tc(a,b,c,d){if(c)if(a=W.getUniform(N[a],P[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else U(1281)}
function Uc(a,b,c,d){if(c)if(a=W.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else U(1281)}function Vc(a){a-=5120;return 0==a?q:1==a?A:2==a?va:4==a?v:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?F:Ja}
function Wc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Xc(a,b,c,d,e){a=Vc(a);var f=Wc(a),k=Gc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+k-1&-k)>>f)}var Yc=[],Zc=[],$c=null,ad=0,bd=null,cd=0,dd=0,ed=0,fd=0,gd=[],hd={},id,jd,kd,ld=!1,md=!1,nd=[];
function kc(){function a(){md=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!od){od=!0;try{pd=!0}catch(c){pd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}qd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:pd?null:console.log("warning: no BlobBuilder");
rd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.pg||"undefined"!==typeof rd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.pg=!0);g.preloadPlugins.push({canHandle:function(c){return!g.pg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var k=null;if(pd)try{k=new Blob([c],{type:sd(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:sd(d)}))}catch(t){ra("Blob constructor present but fails: "+
t+"; falling back to blob builder")}k||(k=new qd,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var l=rd.createObjectURL(k),m=new Image;m.onload=function(){assert(m.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=m.width;t.height=m.height;t.getContext("2d").drawImage(m,0,0);g.preloadedImages[d]=t;rd.revokeObjectURL(l);e&&e(c)};m.onerror=function(){console.log("Image "+l+" could not be decoded");f&&f()};m.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.ih&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function k(u){m||(m=!0,g.preloadedAudios[d]=u,e&&e(c))}function l(){m||(m=!0,g.preloadedAudios[d]=new Audio,f&&f())}var m=!1;if(pd){try{var t=new Blob([c],{type:sd(d)})}catch(u){return l()}t=rd.createObjectURL(t);var r=new Audio;r.addEventListener("canplaythrough",function(){k(r)},!1);r.onerror=function(){if(!m){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",w=0,y=0,
B=0;B<c.length;B++)for(w=w<<8|c[B],y+=8;6<=y;){var D=w>>y-6&63;y-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}2==y?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],u+="=="):4==y&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],u+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+u;k(r)}};r.src=t;td(function(){k(r)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!md&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function ud(a,b,c,d){if(b&&g.uf&&a==g.canvas)return g.uf;var e;if(b){var f={antialias:!1,alpha:!1,ng:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!==typeof Lc&&(e=Jc(a,f)))var l=zc[e].Of}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof W,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.uf=l,b&&(V=zc[e],g.uf=W=V&&V.Of),g.kh=b,nd.forEach(function(m){m()}),kc());return l}
var vd=!1,wd=void 0,xd=void 0;
function yd(a,b){function c(){ld=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=zd,wd&&d.requestPointerLock(),ld=!0,xd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=F[SDL.screen>>2]|8388608),Ad(g.canvas),Bd()):Ad(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),xd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=F[SDL.screen>>2]&
-8388609),Ad(g.canvas),Bd()):Ad(d));if(g.onFullScreen)g.onFullScreen(ld);if(g.onFullscreen)g.onFullscreen(ld)}wd=a;xd=b;"undefined"===typeof wd&&(wd=!0);"undefined"===typeof xd&&(xd=!1);var d=g.canvas;vd||(vd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function zd(){if(!ld)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Cd=0;function Dd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Cd)Cd=b+1E3/60;else for(;b+2>=Cd;)Cd+=1E3/60;setTimeout(a,Math.max(Cd-b,0))}}function td(a){noExitRuntime=!0;setTimeout(function(){za||a()},1E4)}
function sd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Ed=0,Fd=0,Gd=0,Hd=0;
function Id(a){if(md)"mousemove"!=a.type&&"mozMovementX"in a?Gd=Hd=0:(Gd=a.movementX||a.mozMovementX||a.webkitMovementX||0,Hd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Ed=SDL.fh+Gd,Fd=SDL.gh+Hd):(Ed+=Gd,Fd+=Hd);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Gd=e-Ed,Hd=a-Fd,Ed=e,Fd=a)}}function lc(a,b,c){var d="al "+a;la(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Va(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ua(d)}var Jd=[];function Bd(){var a=g.canvas;Jd.forEach(function(b){b(a.width,a.height)})}function Kd(a,b,c){Ad(g.canvas,a,b);c||Bd()}
function Ad(a,b,c){b&&c?(a.Tg=b,a.Fg=c):(b=a.Tg,c=a.Fg);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}xd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var od,pd,qd,rd;
function Ld(a,b){dd=a;ed=b;if(bd)if(0==a)$c=function(){var d=Math.max(0,jd+b-qc())|0;setTimeout(kd,d)};else if(1==a)$c=function(){Dd(kd)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}$c=function(){setImmediate(kd)}}}
function Md(a,b,c,d,e){noExitRuntime=!0;assert(!bd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");bd=a;cd=d;var f=ad;kd=function(){if(!za)if(0<gd.length){var k=Date.now(),l=gd.shift();l.jg(l.Cf);if(id){var m=id,t=0==m%1?m-1:Math.floor(m);id=l.Xg?t:(8*m+(t+.5))/9}console.log('main loop blocker "'+l.name+'" took '+(Date.now()-k)+" ms");g.setStatus&&(k=g.statusMessage||
"Please wait...",l=id,m=hd.Zg,l?l<m?g.setStatus(k+" ("+(m-l)+"/"+m+")"):g.setStatus(k):g.setStatus(""));f<ad||setTimeout(kd,0)}else if(!(f<ad))if(fd=fd+1|0,1==dd&&1<ed&&0!=fd%ed)$c();else{0==dd&&(jd=qc());a:if(!(za||g.preMainLoop&&!1===g.preMainLoop())){try{a()}catch(r){if(r instanceof pa||"unwind"==r)break a;r&&"object"===typeof r&&r.stack&&h("exception thrown: "+[r,r.stack]);throw r;}g.postMainLoop&&g.postMainLoop()}f<ad||("object"===typeof SDL&&SDL.audio&&SDL.audio.Pg&&SDL.audio.Pg(),$c())}};e||
(b&&0<b?Ld(0,1E3/b):Ld(1,1),$c());if(c)throw"unwind";}var Nd={};function Od(){if(!Pd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Nd)a[b]=Nd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Pd=c}return Pd}var Pd;
function Qd(a,b,c,d){this.id=a;this.y=this.x=0;this.Xf=!1;this.ug=this.tg=0;this.width=b;this.height=c;this.sg=b;this.rg=c;this.title=d;this.attributes=Rd;this.buttons=0;this.keys=[];this.Sf=[];this.eg=this.Gf=this.Tf=this.Mf=this.Df=this.Ef=this.Kf=this.Ff=this.wg=this.xg=this.title=null}function Sd(a){return 0>=a||!X?null:X[a-1]}
var Td=null,Y=null,X=null,Rd=null,Ud={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Vd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Wd(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Xd(a){Y&&Y.eg&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||G.get(Y.eg)(Y.id,a))}
function Yd(a,b){if(Y){var c=Vd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Sf[a]=b;Y.Gf&&(d&&(b=2),G.get(Y.Gf)(Y.id,c,a,b,Wd()))}}}function Zd(){$d()}function ae(){$d()}function be(a){Yd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function ce(a){Yd(a.keyCode,0)}function de(){if(Y)for(var a=0;a<Y.Sf.length;++a)Y.Sf[a]&&Yd(a,0)}function ee(a){Y&&(Id(a),a.target==g.canvas&&Y.Ef&&G.get(Y.Ef)(Y.id,Ed,Fd))}function fe(a){Y&&a.target==g.canvas&&Y.Df&&G.get(Y.Df)(Y.id,1)}
function ge(a){Y&&a.target==g.canvas&&Y.Df&&G.get(Y.Df)(Y.id,0)}function he(a,b){if(Y&&(Id(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.Kf&&G.get(Y.Kf)(Y.id,c,b,Wd())}}function ie(a){Y&&he(a,1)}function je(a){Y&&he(a,0)}
function ke(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Mf&&a.target==g.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;G.get(Y.Mf)(Y.id,b,c);a.preventDefault()}}var le={},me=null,oe=null;
function $d(){if(fd!==oe||!fd){me=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;oe=fd;for(var a=0;a<me.length;++a){var b=me[a];if(b){le[a]||(console.log("glfw joystick connected:",a),le[a]={id:Aa(qb(b.id)),Wg:b.buttons.length,Vg:b.axes.length,buttons:Aa(Array(b.buttons.length)),axes:Aa(Array(4*b.axes.length))});for(var c=le[a],d=0;d<b.buttons.length;++d)ua(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)ua(c.axes+4*d,
b.axes[d],"float")}else le[a]&&(console.log("glfw joystick disconnected",a),pe(le[a].id),pe(le[a].buttons),pe(le[a].axes),delete le[a])}}}
function qe(a){function b(l){var m="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(u){if(2!=t.readyState)++f,console.log("failed to read dropped file: "+l.name+": "+t.error);else{var w=new Uint8Array(u.target.result);var y=y||{};y.flags=y.flags||577;u=Wb(m,y.flags,y.mode);if("string"===typeof w){var B=new Uint8Array(Fa(w)+1);w=E(w,B,0,B.length);$b(u,B,0,w,void 0,y.Bg)}else if(ArrayBuffer.isView(w))$b(u,w,0,w.byteLength,void 0,y.Bg);else throw Error("Unsupported data type");
Yb(u);if(++f===e){G.get(Y.Tf)(Y.id,e,c);for(y=0;y<d.length;++y)pe(d[y]);pe(c)}}};t.readAsArrayBuffer(l);var r=Aa(qb(m));d.push(r);ua(c+4*k,r,"i8*")}if(Y&&Y.Tf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Aa(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,f=0;dc("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function re(a){if(Y&&Y.Tf)return a.preventDefault(),!1}var se=[];
function Jb(a,b,c,d){a||(a=this);this.parent=a;this.rf=a.rf;this.Af=null;this.id=Ab++;this.name=b;this.mode=c;this.ff={};this.ef={};this.rdev=d}Object.defineProperties(Jb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Jg:{get:function(){return 16384===(this.mode&61440)}},Ig:{get:function(){return 8192===(this.mode&61440)}}});ac();
Bb=Array(4096);Qb(J,"/");K("/tmp");K("/home");K("/home/web_user");(function(){K("/dev");ob(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Sb("/dev/null",259);nb(1280,rb);nb(1536,sb);Sb("/dev/tty",1280);Sb("/dev/tty1",1536);var a=kb();L("/dev","random",a);L("/dev","urandom",a);K("/dev/shm");K("/dev/shm/tmp")})();
(function(){K("/proc");var a=K("/proc/self");K("/proc/self/fd");Qb({rf:function(){var b=ub(a,"fd",16895,73);b.ff={lookup:function(c,d){var e=zb[+d];if(!e)throw new I(8);c={parent:null,rf:{og:"fake"},ff:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=dc;g.FS_createDataFile=fc;g.FS_createPreloadedFile=jc;g.FS_createLazyFile=ic;g.FS_createDevice=L;g.FS_unlink=Ub;for(var W,Z=0;32>Z;++Z)Mc.push(Array(Z));var te=new Float32Array(288);
for(Z=0;288>Z;++Z)Yc[Z]=te.subarray(0,Z+1);var ue=new Int32Array(288);for(Z=0;288>Z;++Z)Zc[Z]=ue.subarray(0,Z+1);g.requestFullscreen=function(a,b){yd(a,b)};g.requestAnimationFrame=function(a){Dd(a)};g.setCanvasSize=function(a,b,c){Kd(a,b,c)};g.pauseMainLoop=function(){$c=null;ad++};g.resumeMainLoop=function(){ad++;var a=dd,b=ed,c=bd;bd=null;Md(c,0,!1,cd,!0);Ld(a,b);$c()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
g.createContext=function(a,b,c,d){return ud(a,b,c,d)};function qb(a,b){var c=Array(Fa(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var Ae={b:function(a,b,c,d){p("Assertion failed: "+C(a)+", at: "+[b?C(b):"unknown filename",c,d?C(d):"unknown function"])},m:function(a,b,c){nc=c;try{var d=pc(a);switch(b){case 0:var e=oc();return 0>e?-28:Wb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=oc(),d.flags|=e,0;case 12:return e=oc(),va[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return v[ve()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof M&&f instanceof I||
p(f),-f.lf}},La:function(a,b,c){nc=c;try{var d=pc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=oc();return v[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=oc();if(!d.ef.Hg)throw new I(59);return d.ef.Hg(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:p("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof M&&f instanceof I||p(f),
-f.lf}},Ga:function(a,b,c,d,e,f){try{a:{f<<=12;var k=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var m=we(16384,b);if(!m){l=-48;break a}xe(m,0,b);k=!0}else{var t=zb[e];if(!t){l=-8;break a}var r=f;if(0!==(c&2)&&0===(d&2)&&2!==(t.flags&2097155))throw new I(2);if(1===(t.flags&2097155))throw new I(2);if(!t.ef.Jf)throw new I(43);var u=t.ef.Jf(t,a,b,r,c,d);m=u.Og;k=u.Pf}mc[m]={Lg:m,Kg:b,Pf:k,fd:e,Ng:c,flags:d,offset:f};l=m}}return l}catch(w){return"undefined"!==typeof M&&w instanceof I||
p(w),-w.lf}},Fa:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=mc[a];if(d&&b===d.Kg){var e=zb[d.fd];if(e&&d.Ng&2){var f=d.flags,k=d.offset,l=A.slice(a,a+b);e&&e.ef.Lf&&e.ef.Lf(e,l,k,b,f)}mc[a]=null;d.Pf&&pe(d.Lg)}c=0}return c}catch(m){return"undefined"!==typeof M&&m instanceof I||p(m),-m.lf}},eb:function(a,b,c){nc=c;try{var d=C(a),e=c?oc():0;return Wb(d,b,e).fd}catch(f){return"undefined"!==typeof M&&f instanceof I||p(f),-f.lf}},Ba:function(){p()},i:function(a,b){if(0===a)a=Date.now();
else if(1===a||4===a)a=qc();else return v[ve()>>2]=28,-1;v[b>>2]=a/1E3|0;v[b+4>>2]=a%1E3*1E6|0;return 0},c:function(a,b,c){se.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,se.push(d?xa[c++>>1]:v[c]),++c;return cb[a].apply(null,se)},da:function(a){W.activeTexture(a)},ca:function(a,b){W.attachShader(N[a],Q[b])},uc:function(a,b){W.beginQuery(a,Ac[b])},va:function(a,b){W.nf.beginQueryEXT(a,S[b])},bc:function(a){W.beginTransformFeedback(a)},ba:function(a,b,c){W.bindAttribLocation(N[a],b,C(c))},
aa:function(a,b){35051==a?W.Rf=b:35052==a&&(W.pf=b);W.bindBuffer(a,vc[b])},_b:function(a,b,c){W.bindBufferBase(a,b,vc[c])},$b:function(a,b,c,d,e){W.bindBufferRange(a,b,vc[c],d,e)},$:function(a,b){W.bindFramebuffer(a,wc[b])},_:function(a,b){W.bindRenderbuffer(a,xc[b])},gb:function(a,b){W.bindSampler(a,T[b])},Z:function(a,b){W.bindTexture(a,yc[b])},Za:function(a,b){W.bindTransformFeedback(a,Bc[b])},gc:function(a){W.bindVertexArray(R[a])},ma:function(a){W.bindVertexArray(R[a])},Y:function(a,b,c,d){W.blendColor(a,
b,c,d)},X:function(a){W.blendEquation(a)},W:function(a,b){W.blendEquationSeparate(a,b)},U:function(a,b){W.blendFunc(a,b)},T:function(a,b,c,d){W.blendFuncSeparate(a,b,c,d)},jc:function(a,b,c,d,e,f,k,l,m,t){W.blitFramebuffer(a,b,c,d,e,f,k,l,m,t)},S:function(a,b,c,d){2<=V.version?c?W.bufferData(a,A,d,c,b):W.bufferData(a,b,d):W.bufferData(a,c?A.subarray(c,c+b):b,d)},R:function(a,b,c,d){2<=V.version?W.bufferSubData(a,b,A,d,c):W.bufferSubData(a,b,A.subarray(d,d+c))},Q:function(a){return W.checkFramebufferStatus(a)},
P:function(a){W.clear(a)},Db:function(a,b,c,d){W.clearBufferfi(a,b,c,d)},Eb:function(a,b,c){W.clearBufferfv(a,b,z,c>>2)},Gb:function(a,b,c){W.clearBufferiv(a,b,v,c>>2)},Fb:function(a,b,c){W.clearBufferuiv(a,b,F,c>>2)},O:function(a,b,c,d){W.clearColor(a,b,c,d)},N:function(a){W.clearDepth(a)},M:function(a){W.clearStencil(a)},pb:function(a,b,c,d){return W.clientWaitSync(Cc[a],b,(c>>>0)+4294967296*d)},L:function(a,b,c,d){W.colorMask(!!a,!!b,!!c,!!d)},J:function(a){W.compileShader(Q[a])},I:function(a,
b,c,d,e,f,k,l){2<=V.version?W.pf?W.compressedTexImage2D(a,b,c,d,e,f,k,l):W.compressedTexImage2D(a,b,c,d,e,f,A,l,k):W.compressedTexImage2D(a,b,c,d,e,f,l?A.subarray(l,l+k):null)},Ac:function(a,b,c,d,e,f,k,l,m){W.pf?W.compressedTexImage3D(a,b,c,d,e,f,k,l,m):W.compressedTexImage3D(a,b,c,d,e,f,k,A,m,l)},H:function(a,b,c,d,e,f,k,l,m){2<=V.version?W.pf?W.compressedTexSubImage2D(a,b,c,d,e,f,k,l,m):W.compressedTexSubImage2D(a,b,c,d,e,f,k,A,m,l):W.compressedTexSubImage2D(a,b,c,d,e,f,k,m?A.subarray(m,m+l):null)},
zc:function(a,b,c,d,e,f,k,l,m,t,r){W.pf?W.compressedTexSubImage3D(a,b,c,d,e,f,k,l,m,t,r):W.compressedTexSubImage3D(a,b,c,d,e,f,k,l,m,A,r,t)},Bb:function(a,b,c,d,e){W.copyBufferSubData(a,b,c,d,e)},G:function(a,b,c,d,e,f,k,l){W.copyTexImage2D(a,b,c,d,e,f,k,l)},F:function(a,b,c,d,e,f,k,l){W.copyTexSubImage2D(a,b,c,d,e,f,k,l)},Bc:function(a,b,c,d,e,f,k,l,m){W.copyTexSubImage3D(a,b,c,d,e,f,k,l,m)},E:function(){var a=Ic(N),b=W.createProgram();b.name=a;N[a]=b;return a},D:function(a){var b=Ic(Q);Q[b]=W.createShader(a);
return b},C:function(a){W.cullFace(a)},B:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=vc[d];e&&(W.deleteBuffer(e),e.name=0,vc[d]=null,d==W.Rf&&(W.Rf=0),d==W.pf&&(W.pf=0))}},A:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=wc[d];e&&(W.deleteFramebuffer(e),e.name=0,wc[d]=null)}},y:function(a){if(a){var b=N[a];b?(W.deleteProgram(b),b.name=0,N[a]=null,Dc[a]=null):U(1281)}},xc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Ac[d];e&&(W.deleteQuery(e),Ac[d]=null)}},xa:function(a,
b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(W.nf.deleteQueryEXT(e),S[d]=null)}},x:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xc[d];e&&(W.deleteRenderbuffer(e),e.name=0,xc[d]=null)}},ib:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=T[d];e&&(W.deleteSampler(e),e.name=0,T[d]=null)}},w:function(a){if(a){var b=Q[a];b?(W.deleteShader(b),Q[a]=null):U(1281)}},qb:function(a){if(a){var b=Cc[a];b?(W.deleteSync(b),b.name=0,Cc[a]=null):U(1281)}},v:function(a,b){for(var c=0;c<a;c++){var d=
v[b+4*c>>2],e=yc[d];e&&(W.deleteTexture(e),e.name=0,yc[d]=null)}},Ya:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Bc[d];e&&(W.deleteTransformFeedback(e),e.name=0,Bc[d]=null)}},fc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];W.deleteVertexArray(R[d]);R[d]=null}},la:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];W.deleteVertexArray(R[d]);R[d]=null}},u:function(a){W.depthFunc(a)},t:function(a){W.depthMask(!!a)},s:function(a,b){W.depthRange(a,b)},r:function(a,b){W.detachShader(N[a],
Q[b])},q:function(a){W.disable(a)},p:function(a){W.disableVertexAttribArray(a)},Re:function(a,b,c){W.drawArrays(a,b,c)},ub:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},ha:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Lc:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Mc:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Ja:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},qc:function(a,b){for(var c=Mc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},Hc:function(a,b){for(var c=Mc[a],d=0;d<
a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},ia:function(a,b){for(var c=Mc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},Qe:function(a,b,c,d){W.drawElements(a,b,c,d)},tb:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},ga:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Ic:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Jc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Kc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Ec:function(a,b,c,d,e,f){W.drawElements(a,
d,e,f)},Pe:function(a){W.enable(a)},Oe:function(a){W.enableVertexAttribArray(a)},tc:function(a){W.endQuery(a)},ua:function(a){W.nf.endQueryEXT(a)},ac:function(){W.endTransformFeedback()},sb:function(a,b){return(a=W.fenceSync(a,b))?(b=Ic(Cc),a.name=b,Cc[b]=a,b):0},Ne:function(){W.finish()},Me:function(){W.flush()},Le:function(a,b,c,d){W.framebufferRenderbuffer(a,b,c,xc[d])},Ke:function(a,b,c,d,e){W.framebufferTexture2D(a,b,c,yc[d],e)},hc:function(a,b,c,d,e){W.framebufferTextureLayer(a,b,yc[c],d,e)},
Je:function(a){W.frontFace(a)},Ie:function(a,b){Nc(a,b,"createBuffer",vc)},Fe:function(a,b){Nc(a,b,"createFramebuffer",wc)},yc:function(a,b){Nc(a,b,"createQuery",Ac)},ya:function(a,b){for(var c=0;c<a;c++){var d=W.nf.createQueryEXT();if(!d){for(U(1282);c<a;)v[b+4*c++>>2]=0;break}var e=Ic(S);d.name=e;S[e]=d;v[b+4*c>>2]=e}},Ee:function(a,b){Nc(a,b,"createRenderbuffer",xc)},jb:function(a,b){Nc(a,b,"createSampler",T)},De:function(a,b){Nc(a,b,"createTexture",yc)},Xa:function(a,b){Nc(a,b,"createTransformFeedback",
Bc)},ec:function(a,b){Nc(a,b,"createVertexArray",R)},ka:function(a,b){Nc(a,b,"createVertexArray",R)},Ge:function(a){W.generateMipmap(a)},Ce:function(a,b,c,d,e,f,k){Oc("getActiveAttrib",a,b,c,d,e,f,k)},Be:function(a,b,c,d,e,f,k){Oc("getActiveUniform",a,b,c,d,e,f,k)},wb:function(a,b,c,d,e){a=N[a];if(a=W.getActiveUniformBlockName(a,b))e&&0<c?(c=E(a,A,e,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0)},xb:function(a,b,c,d){if(d)switch(a=N[a],c){case 35393:a=W.getActiveUniformBlockName(a,b);v[d>>2]=a.length+1;break;
default:if(a=W.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)v[d>>2]=a;else for(b=0;b<a.length;b++)v[d+4*b>>2]=a[b]}else U(1281)},zb:function(a,b,c,d,e){if(e)if(0<b&&0==c)U(1281);else{a=N[a];for(var f=[],k=0;k<b;k++)f.push(v[c+4*k>>2]);if(a=W.getActiveUniforms(a,f,d))for(b=a.length,k=0;k<b;k++)v[e+4*k>>2]=a[k]}else U(1281)},Ae:function(a,b,c,d){a=W.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=Q.indexOf(a[b])},ze:function(a,b){return W.getAttribLocation(N[a],
C(b))},ye:function(a,b){Qc(a,b,4)},kb:function(a,b,c){c?Pc(c,W.getBufferParameter(a,b)):U(1281)},xe:function(a,b,c){c?v[c>>2]=W.getBufferParameter(a,b):U(1281)},ve:function(){var a=W.getError()||Hc;Hc=0;return a},ue:function(a,b){Qc(a,b,2)},Pb:function(a,b){return W.getFragDataLocation(N[a],C(b))},te:function(a,b,c,d){a=W.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},lb:function(a,b,c){Rc(a,b,c,1)},nb:function(a,b){Qc(a,
b,1)},cc:function(a,b,c){Rc(a,b,c,0)},se:function(a,b){Qc(a,b,0)},Ma:function(a,b,c,d,e){if(0>d)U(1281);else if(e){if(a=W.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)v[e+b>>2]=a[b]}else U(1281)},Ta:function(){U(1282)},qe:function(a,b,c,d){a=W.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,A,d,b):0;c&&(v[c>>2]=b)},re:function(a,b,c){if(c)if(a>=uc)U(1281);else{var d=Dc[a];if(d)if(35716==b)a=W.getProgramInfoLog(N[a]),null===a&&(a="(unknown error)"),v[c>>
2]=a.length+1;else if(35719==b)v[c>>2]=d.$f;else if(35722==b){if(-1==d.yf){a=N[a];var e=W.getProgramParameter(a,35721);for(b=d.yf=0;b<e;++b)d.yf=Math.max(d.yf,W.getActiveAttrib(a,b).name.length+1)}v[c>>2]=d.yf}else if(35381==b){if(-1==d.zf)for(a=N[a],e=W.getProgramParameter(a,35382),b=d.zf=0;b<e;++b)d.zf=Math.max(d.zf,W.getActiveUniformBlockName(a,b).length+1);v[c>>2]=d.zf}else v[c>>2]=W.getProgramParameter(N[a],b);else U(1282)}else U(1281)},oa:function(a,b,c){if(c){a=W.nf.getQueryObjectEXT(S[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;Pc(c,d)}else U(1281)},ra:function(a,b,c){if(c){a=W.nf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else U(1281)},na:function(a,b,c){if(c){a=W.nf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Pc(c,d)}else U(1281)},rc:function(a,b,c){if(c){a=W.getQueryParameter(Ac[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else U(1281)},qa:function(a,b,c){if(c){a=W.nf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;v[c>>2]=d}else U(1281)},sc:function(a,b,c){c?v[c>>2]=W.getQuery(a,b):U(1281)},sa:function(a,b,c){c?v[c>>2]=W.nf.getQueryEXT(a,b):U(1281)},pe:function(a,b,c){c?v[c>>2]=W.getRenderbufferParameter(a,b):U(1281)},$a:function(a,b,c){c?(a=T[a],z[c>>2]=W.getSamplerParameter(a,b)):U(1281)},ab:function(a,b,c){c?(a=T[a],v[c>>2]=W.getSamplerParameter(a,b)):U(1281)},ne:function(a,b,c,d){a=W.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,A,d,b):0;c&&(v[c>>2]=b)},me:function(a,b,
c,d){a=W.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},le:function(a,b,c,d){if(a=W.getShaderSource(Q[a]))b=0<b&&d?E(a,A,d,b):0,c&&(v[c>>2]=b)},oe:function(a,b,c){c?35716==b?(a=W.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=W.getShaderSource(Q[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=W.getShaderParameter(Q[a],b):U(1281)},ke:function(a){if(Ec[a])return Ec[a];switch(a){case 7939:var b=W.getSupportedExtensions()||[];
b=b.concat(b.map(function(d){return"GL_"+d}));b=Sc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=W.getParameter(a))||U(1280);b=Sc(b);break;case 7938:b=W.getParameter(7938);b=2<=V.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Sc(b);break;case 35724:b=W.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Sc(b);break;default:return U(1280),0}return Ec[a]=b},Cb:function(a,
b){if(2>V.version)return U(1282),0;var c=Fc[a];if(c)return 0>b||b>=c.length?(U(1281),0):c[b];switch(a){case 7939:return c=W.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Sc(d)}),c=Fc[a]=c,0>b||b>=c.length?(U(1281),0):c[b];default:return U(1280),0}},mb:function(a,b,c,d,e){0>c?U(1281):e?(a=W.getSyncParameter(Cc[a],b),v[d>>2]=a,null!==a&&d&&(v[d>>2]=1)):U(1281)},je:function(a,b,c){c?z[c>>2]=W.getTexParameter(a,b):U(1281)},ie:function(a,b,c){c?v[c>>
2]=W.getTexParameter(a,b):U(1281)},Yb:function(a,b,c,d,e,f,k){a=N[a];if(a=W.getTransformFeedbackVarying(a,b))k&&0<c?(c=E(a.name,A,k,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0),e&&(v[e>>2]=a.size),f&&(v[f>>2]=a.type)},yb:function(a,b){return W.getUniformBlockIndex(N[a],C(b))},Ab:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))U(1281);else{a=N[a];for(var e=[],f=0;f<b;f++)e.push(C(v[c+4*f>>2]));if(a=W.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)v[d+4*f>>2]=a[f]}else U(1281)},fe:function(a,b){b=C(b);var c=0;
if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Dc[a]&&Dc[a].vg[b])&&0<=c&&c<a[0]?a[1]+c:-1},he:function(a,b,c){Tc(a,b,c,2)},ge:function(a,b,c){Tc(a,b,c,0)},Qb:function(a,b,c){Tc(a,b,c,0)},Wb:function(a,b,c){Uc(a,b,c,0)},Vb:function(a,b,c){Uc(a,b,c,0)},ce:function(a,b,c){c?v[c>>2]=W.getVertexAttribOffset(a,b):U(1281)},ee:function(a,b,c){Uc(a,b,c,2)},de:function(a,b,c){Uc(a,b,c,5)},ae:function(a,b){W.hint(a,b)},Qa:function(a,b,c){for(var d=
Mc[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];W.invalidateFramebuffer(a,d)},Pa:function(a,b,c,d,e,f,k){for(var l=Mc[b],m=0;m<b;m++)l[m]=v[c+4*m>>2];W.invalidateSubFramebuffer(a,l,d,e,f,k)},$d:function(a){return(a=vc[a])?W.isBuffer(a):0},_d:function(a){return W.isEnabled(a)},Zd:function(a){return(a=wc[a])?W.isFramebuffer(a):0},Yd:function(a){return(a=N[a])?W.isProgram(a):0},wc:function(a){return(a=Ac[a])?W.isQuery(a):0},wa:function(a){return(a=S[a])?W.nf.isQueryEXT(a):0},Xd:function(a){return(a=xc[a])?W.isRenderbuffer(a):
0},hb:function(a){return(a=T[a])?W.isSampler(a):0},Wd:function(a){return(a=Q[a])?W.isShader(a):0},rb:function(a){return W.isSync(Cc[a])},Vd:function(a){return(a=yc[a])?W.isTexture(a):0},Wa:function(a){return W.isTransformFeedback(Bc[a])},dc:function(a){return(a=R[a])?W.isVertexArray(a):0},ja:function(a){return(a=R[a])?W.isVertexArray(a):0},Ud:function(a){W.lineWidth(a)},Td:function(a){W.linkProgram(N[a]);var b=N[a];a=Dc[a]={vg:{},$f:0,yf:-1,zf:-1};for(var c=a.vg,d=W.getProgramParameter(b,35718),e=
0;e<d;++e){var f=W.getActiveUniform(b,e),k=f.name;a.$f=Math.max(a.$f,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var l=W.getUniformLocation(b,k);if(l){var m=Ic(P);c[k]=[f.size,m];P[m]=l;for(var t=1;t<f.size;++t)l=W.getUniformLocation(b,k+"["+t+"]"),m=Ic(P),P[m]=l}}},Va:function(){W.pauseTransformFeedback()},Rd:function(a,b){3317==a&&(Gc=b);W.pixelStorei(a,b)},Qd:function(a,b){W.polygonOffset(a,b)},Sa:function(){U(1280)},Ra:function(){U(1280)},ta:function(a,b){W.nf.queryCounterEXT(S[a],
b)},Fc:function(a){W.readBuffer(a)},Pd:function(a,b,c,d,e,f,k){if(2<=V.version)if(W.Rf)W.readPixels(a,b,c,d,e,f,k);else{var l=Vc(f);W.readPixels(a,b,c,d,e,f,l,k>>Wc(l))}else(k=Xc(f,e,c,d,k))?W.readPixels(a,b,c,d,e,f,k):U(1280)},Od:function(){},Nd:function(a,b,c,d){W.renderbufferStorage(a,b,c,d)},ic:function(a,b,c,d,e){W.renderbufferStorageMultisample(a,b,c,d,e)},Ua:function(){W.resumeTransformFeedback()},Md:function(a,b){W.sampleCoverage(a,!!b)},cb:function(a,b,c){W.samplerParameterf(T[a],b,c)},bb:function(a,
b,c){W.samplerParameterf(T[a],b,z[c>>2])},fb:function(a,b,c){W.samplerParameteri(T[a],b,c)},db:function(a,b,c){W.samplerParameteri(T[a],b,v[c>>2])},Ld:function(a,b,c,d){W.scissor(a,b,c,d)},Kd:function(){U(1280)},Jd:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?v[d+4*f>>2]:-1;e+=C(v[c+4*f>>2],0>k?void 0:k)}W.shaderSource(Q[a],e)},Id:function(a,b,c){W.stencilFunc(a,b,c)},Gd:function(a,b,c,d){W.stencilFuncSeparate(a,b,c,d)},Fd:function(a){W.stencilMask(a)},Ed:function(a,b){W.stencilMaskSeparate(a,
b)},Dd:function(a,b,c){W.stencilOp(a,b,c)},Cd:function(a,b,c,d){W.stencilOpSeparate(a,b,c,d)},Bd:function(a,b,c,d,e,f,k,l,m){if(2<=V.version)if(W.pf)W.texImage2D(a,b,c,d,e,f,k,l,m);else if(m){var t=Vc(l);W.texImage2D(a,b,c,d,e,f,k,l,t,m>>Wc(t))}else W.texImage2D(a,b,c,d,e,f,k,l,null);else W.texImage2D(a,b,c,d,e,f,k,l,m?Xc(l,k,d,e,m):null)},Dc:function(a,b,c,d,e,f,k,l,m,t){if(W.pf)W.texImage3D(a,b,c,d,e,f,k,l,m,t);else if(t){var r=Vc(m);W.texImage3D(a,b,c,d,e,f,k,l,m,r,t>>Wc(r))}else W.texImage3D(a,
b,c,d,e,f,k,l,m,null)},Ad:function(a,b,c){W.texParameterf(a,b,c)},zd:function(a,b,c){W.texParameterf(a,b,z[c>>2])},yd:function(a,b,c){W.texParameteri(a,b,c)},xd:function(a,b,c){W.texParameteri(a,b,v[c>>2])},Oa:function(a,b,c,d,e){W.texStorage2D(a,b,c,d,e)},Na:function(a,b,c,d,e,f){W.texStorage3D(a,b,c,d,e,f)},vd:function(a,b,c,d,e,f,k,l,m){if(2<=V.version)if(W.pf)W.texSubImage2D(a,b,c,d,e,f,k,l,m);else if(m){var t=Vc(l);W.texSubImage2D(a,b,c,d,e,f,k,l,t,m>>Wc(t))}else W.texSubImage2D(a,b,c,d,e,f,
k,l,null);else t=null,m&&(t=Xc(l,k,e,f,m)),W.texSubImage2D(a,b,c,d,e,f,k,l,t)},Cc:function(a,b,c,d,e,f,k,l,m,t,r){if(W.pf)W.texSubImage3D(a,b,c,d,e,f,k,l,m,t,r);else if(r){var u=Vc(t);W.texSubImage3D(a,b,c,d,e,f,k,l,m,t,u,r>>Wc(u))}else W.texSubImage3D(a,b,c,d,e,f,k,l,m,t,null)},Zb:function(a,b,c,d){a=N[a];for(var e=[],f=0;f<b;f++)e.push(C(v[c+4*f>>2]));W.transformFeedbackVaryings(a,e,d)},ud:function(a,b){W.uniform1f(P[a],b)},td:function(a,b,c){if(2<=V.version)W.uniform1fv(P[a],z,c>>2,b);else{if(288>=
b)for(var d=Yc[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);W.uniform1fv(P[a],d)}},sd:function(a,b){W.uniform1i(P[a],b)},rd:function(a,b,c){if(2<=V.version)W.uniform1iv(P[a],v,c>>2,b);else{if(288>=b)for(var d=Zc[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);W.uniform1iv(P[a],d)}},Ob:function(a,b){W.uniform1ui(P[a],b)},Kb:function(a,b,c){W.uniform1uiv(P[a],F,c>>2,b)},qd:function(a,b,c){W.uniform2f(P[a],b,c)},pd:function(a,b,c){if(2<=V.version)W.uniform2fv(P[a],
z,c>>2,2*b);else{if(144>=b)for(var d=Yc[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);W.uniform2fv(P[a],d)}},od:function(a,b,c){W.uniform2i(P[a],b,c)},nd:function(a,b,c){if(2<=V.version)W.uniform2iv(P[a],v,c>>2,2*b);else{if(144>=b)for(var d=Zc[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);W.uniform2iv(P[a],d)}},Nb:function(a,b,c){W.uniform2ui(P[a],b,c)},Jb:function(a,b,c){W.uniform2uiv(P[a],F,c>>2,2*
b)},md:function(a,b,c,d){W.uniform3f(P[a],b,c,d)},kd:function(a,b,c){if(2<=V.version)W.uniform3fv(P[a],z,c>>2,3*b);else{if(96>=b)for(var d=Yc[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);W.uniform3fv(P[a],d)}},jd:function(a,b,c,d){W.uniform3i(P[a],b,c,d)},id:function(a,b,c){if(2<=V.version)W.uniform3iv(P[a],v,c>>2,3*b);else{if(96>=b)for(var d=Zc[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>
2];else d=v.subarray(c>>2,c+12*b>>2);W.uniform3iv(P[a],d)}},Mb:function(a,b,c,d){W.uniform3ui(P[a],b,c,d)},Ib:function(a,b,c){W.uniform3uiv(P[a],F,c>>2,3*b)},hd:function(a,b,c,d,e){W.uniform4f(P[a],b,c,d,e)},gd:function(a,b,c){if(2<=V.version)W.uniform4fv(P[a],z,c>>2,4*b);else{if(72>=b){var d=Yc[4*b-1],e=z;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];d[f+3]=e[k+3]}}else d=z.subarray(c>>2,c+16*b>>2);W.uniform4fv(P[a],d)}},fd:function(a,b,c,d,e){W.uniform4i(P[a],b,c,
d,e)},ed:function(a,b,c){if(2<=V.version)W.uniform4iv(P[a],v,c>>2,4*b);else{if(72>=b)for(var d=Zc[4*b-1],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);W.uniform4iv(P[a],d)}},Lb:function(a,b,c,d,e){W.uniform4ui(P[a],b,c,d,e)},Hb:function(a,b,c){W.uniform4uiv(P[a],F,c>>2,4*b)},vb:function(a,b,c){a=N[a];W.uniformBlockBinding(a,b,c)},dd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix2fv(P[a],!!c,z,d>>2,4*b);else{if(72>=
b)for(var e=Yc[4*b-1],f=0;f<4*b;f+=4)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2];else e=z.subarray(d>>2,d+16*b>>2);W.uniformMatrix2fv(P[a],!!c,e)}},pc:function(a,b,c,d){W.uniformMatrix2x3fv(P[a],!!c,z,d>>2,6*b)},nc:function(a,b,c,d){W.uniformMatrix2x4fv(P[a],!!c,z,d>>2,8*b)},cd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix3fv(P[a],!!c,z,d>>2,9*b);else{if(32>=b)for(var e=Yc[9*b-1],f=0;f<9*b;f+=9)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+
8)>>2],e[f+3]=z[d+(4*f+12)>>2],e[f+4]=z[d+(4*f+16)>>2],e[f+5]=z[d+(4*f+20)>>2],e[f+6]=z[d+(4*f+24)>>2],e[f+7]=z[d+(4*f+28)>>2],e[f+8]=z[d+(4*f+32)>>2];else e=z.subarray(d>>2,d+36*b>>2);W.uniformMatrix3fv(P[a],!!c,e)}},oc:function(a,b,c,d){W.uniformMatrix3x2fv(P[a],!!c,z,d>>2,6*b)},lc:function(a,b,c,d){W.uniformMatrix3x4fv(P[a],!!c,z,d>>2,12*b)},bd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix4fv(P[a],!!c,z,d>>2,16*b);else{if(18>=b){var e=Yc[16*b-1],f=z;d>>=2;for(var k=0;k<16*b;k+=16){var l=d+
k;e[k]=f[l];e[k+1]=f[l+1];e[k+2]=f[l+2];e[k+3]=f[l+3];e[k+4]=f[l+4];e[k+5]=f[l+5];e[k+6]=f[l+6];e[k+7]=f[l+7];e[k+8]=f[l+8];e[k+9]=f[l+9];e[k+10]=f[l+10];e[k+11]=f[l+11];e[k+12]=f[l+12];e[k+13]=f[l+13];e[k+14]=f[l+14];e[k+15]=f[l+15]}}else e=z.subarray(d>>2,d+64*b>>2);W.uniformMatrix4fv(P[a],!!c,e)}},mc:function(a,b,c,d){W.uniformMatrix4x2fv(P[a],!!c,z,d>>2,8*b)},kc:function(a,b,c,d){W.uniformMatrix4x3fv(P[a],!!c,z,d>>2,12*b)},$c:function(a){W.useProgram(N[a])},_c:function(a){W.validateProgram(N[a])},
Zc:function(a,b){W.vertexAttrib1f(a,b)},Yc:function(a,b){W.vertexAttrib1f(a,z[b>>2])},Xc:function(a,b,c){W.vertexAttrib2f(a,b,c)},Wc:function(a,b){W.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},Vc:function(a,b,c,d){W.vertexAttrib3f(a,b,c,d)},Uc:function(a,b){W.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},Tc:function(a,b,c,d,e){W.vertexAttrib4f(a,b,c,d,e)},Sc:function(a,b){W.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},_a:function(a,b){W.vertexAttribDivisor(a,b)},fa:function(a,b){W.vertexAttribDivisor(a,
b)},Nc:function(a,b){W.vertexAttribDivisor(a,b)},Oc:function(a,b){W.vertexAttribDivisor(a,b)},Ka:function(a,b){W.vertexAttribDivisor(a,b)},Ub:function(a,b,c,d,e){W.vertexAttribI4i(a,b,c,d,e)},Sb:function(a,b){W.vertexAttribI4i(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Tb:function(a,b,c,d,e){W.vertexAttribI4ui(a,b,c,d,e)},Rb:function(a,b){W.vertexAttribI4ui(a,F[b>>2],F[b+4>>2],F[b+8>>2],F[b+12>>2])},Xb:function(a,b,c,d,e){W.vertexAttribIPointer(a,b,c,d,e)},Qc:function(a,b,c,d,e,f){W.vertexAttribPointer(a,
b,c,!!d,e,f)},Pc:function(a,b,c,d){W.viewport(a,b,c,d)},ob:function(a,b,c,d){W.waitSync(Cc[a],b,(c>>>0)+4294967296*d)},f:function(){return 0},za:function(a,b,c){A.copyWithin(a,b,b+c)},d:function(a){a>>>=0;var b=A.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ya.grow(Math.min(2147483648,d)-Ia.byteLength+65535>>>16);Ka();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Aa:function(a,
b,c,d,e){a=G.get(a);Md(a,b,c,d,e)},e:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ea:function(a){for(var b=qc();qc()-b<a;);},Ca:function(a,b){try{var c=0;Od().forEach(function(d,e){var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++>>0]=d.charCodeAt(f);q[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof M&&d instanceof I||p(d),d.lf}},Da:function(a,b){try{var c=Od();v[a>>2]=c.length;var d=0;c.forEach(function(e){d+=
e.length+1});v[b>>2]=d;return 0}catch(e){return"undefined"!==typeof M&&e instanceof I||p(e),e.lf}},k:function(a){ye(a)},n:function(a){try{var b=pc(a);Yb(b);return 0}catch(c){return"undefined"!==typeof M&&c instanceof I||p(c),c.lf}},Ha:function(a,b,c,d){try{a:{for(var e=pc(a),f=a=0;f<c;f++){var k=v[b+(8*f+4)>>2],l=e,m=v[b+8*f>>2],t=k,r=void 0,u=q;if(0>t||0>r)throw new I(28);if(null===l.fd)throw new I(8);if(1===(l.flags&2097155))throw new I(8);if(16384===(l.node.mode&61440))throw new I(31);if(!l.ef.read)throw new I(28);
var w="undefined"!==typeof r;if(!w)r=l.position;else if(!l.seekable)throw new I(70);var y=l.ef.read(l,u,m,t,r);w||(l.position+=y);var B=y;if(0>B){var D=-1;break a}a+=B;if(B<k)break}D=a}v[d>>2]=D;return 0}catch(H){return"undefined"!==typeof M&&H instanceof I||p(H),H.lf}},Ia:function(a,b,c,d,e){try{var f=pc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Zb(f,a,d);wa=[f.position>>>0,(x=f.position,1<=+Math.abs(x)?0<x?(Math.min(+Math.floor(x/4294967296),4294967295)|0)>>>
0:~~+Math.ceil((x-+(~~x>>>0))/4294967296)>>>0:0)];v[e>>2]=wa[0];v[e+4>>2]=wa[1];f.Yf&&0===a&&0===d&&(f.Yf=null);return 0}catch(k){return"undefined"!==typeof M&&k instanceof I||p(k),k.lf}},o:function(a,b,c,d){try{a:{for(var e=pc(a),f=a=0;f<c;f++){var k=$b(e,q,v[b+8*f>>2],v[b+(8*f+4)>>2],void 0);if(0>k){var l=-1;break a}a+=k}l=a}v[d>>2]=l;return 0}catch(m){return"undefined"!==typeof M&&m instanceof I||p(m),m.lf}},j:function(a){var b=Date.now();v[a>>2]=b/1E3|0;v[a+4>>2]=b%1E3*1E3|0;return 0},He:function(a,
b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?yd():Kd(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<Rd[139265];e==X.length&&(d?g.uf=ud(g.canvas,!0,!0,{antialias:1<Rd[135181],depth:0<Rd[135173],stencil:0<Rd[135174],alpha:0<Rd[135172]}):kc());!g.uf&&d?f=0:(a=new Qd(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id)}return f},z:function(){Rd=Ud},Gc:function(a){a:{if(a=Sd(a)){a.wg&&G.get(a.wg)(a.id);
X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}g.uf=void 0}a=void 0}return a},ad:function(a,b,c){ua(b,Ed,"double");ua(c,Fd,"double")},Rc:function(a,b,c){var d=0,e=0;if(a=Sd(a))d=a.width,e=a.height;b&&ua(b,d,"i32");c&&ua(c,e,"i32")},a:function(a){return ze(a)},K:function(){if(X)return 1;qc();Rd=Ud;X=[];Y=null;window.addEventListener("gamepadconnected",Zd,!0);window.addEventListener("gamepaddisconnected",ae,!0);window.addEventListener("keydown",be,!0);window.addEventListener("keypress",
Xd,!0);window.addEventListener("keyup",ce,!0);window.addEventListener("blur",de,!0);g.canvas.addEventListener("touchmove",ee,!0);g.canvas.addEventListener("touchstart",ie,!0);g.canvas.addEventListener("touchcancel",je,!0);g.canvas.addEventListener("touchend",je,!0);g.canvas.addEventListener("mousemove",ee,!0);g.canvas.addEventListener("mousedown",ie,!0);g.canvas.addEventListener("mouseup",je,!0);g.canvas.addEventListener("wheel",ke,!0);g.canvas.addEventListener("mousewheel",ke,!0);g.canvas.addEventListener("mouseenter",
fe,!0);g.canvas.addEventListener("mouseleave",ge,!0);g.canvas.addEventListener("drop",qe,!0);g.canvas.addEventListener("dragover",re,!0);Jd.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.tg=Y.x,Y.ug=Y.y,Y.sg=Y.width,Y.rg=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Xf=!0):1==Y.Xf?(Y.x=Y.tg,Y.y=Y.ug,Y.width=Y.sg,Y.height=Y.rg,Y.Xf=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(Kd(Y.width,
Y.height,!0),Y&&Y.xg&&G.get(Y.xg)(Y.id,Y.width,Y.height),Y&&Y.Ff&&G.get(Y.Ff)(Y.id,Y.width,Y.height))}});return 1},we:function(){},pa:function(){},Sd:function(a,b){if(a=Sd(a)){var c=a.Ef;a.Ef=b;b=c}else b=null;return b},V:function(a){var b=Td;Td=a;return b},be:function(a,b){a=Sd(a);if(!a)return null;var c=a.Ff;a.Ff=b;return c},Hd:function(a,b){if(a=Sd(a)){var c=a.Gf;a.Gf=b;b=c}else b=null;return b},ld:function(a,b){if(a=Sd(a)){var c=a.Kf;a.Kf=b;b=c}else b=null;return b},wd:function(a,b){if(a=Sd(a)){var c=
a.Mf;a.Mf=b;b=c}else b=null;return b},ea:function(){},vc:function(){window.removeEventListener("gamepadconnected",Zd,!0);window.removeEventListener("gamepaddisconnected",ae,!0);window.removeEventListener("keydown",be,!0);window.removeEventListener("keypress",Xd,!0);window.removeEventListener("keyup",ce,!0);window.removeEventListener("blur",de,!0);g.canvas.removeEventListener("touchmove",ee,!0);g.canvas.removeEventListener("touchstart",ie,!0);g.canvas.removeEventListener("touchcancel",je,!0);g.canvas.removeEventListener("touchend",
je,!0);g.canvas.removeEventListener("mousemove",ee,!0);g.canvas.removeEventListener("mousedown",ie,!0);g.canvas.removeEventListener("mouseup",je,!0);g.canvas.removeEventListener("wheel",ke,!0);g.canvas.removeEventListener("mousewheel",ke,!0);g.canvas.removeEventListener("mouseenter",fe,!0);g.canvas.removeEventListener("mouseleave",ge,!0);g.canvas.removeEventListener("drop",qe,!0);g.canvas.removeEventListener("dragover",re,!0);g.canvas.width=g.canvas.height=1;Y=X=null},h:function(a,b){Rd[a]=b},l:function(){},
g:function(){return 0}};
(function(){function a(e){g.asm=e.exports;ya=g.asm.Se;Ka();G=g.asm.Te;Va("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return ab().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){h("failed to asynchronously prepare wasm: "+f);p(f)})}var d={a:Ae};Ua("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return h("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ta||"function"!==typeof WebAssembly.instantiateStreaming||
Ya()||Wa("file://")||"function"!==typeof fetch?c(b):fetch(Xa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){h("wasm streaming compile failed: "+f);h("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Pa=g.___wasm_call_ctors=function(){return(Pa=g.___wasm_call_ctors=g.asm.Ue).apply(null,arguments)},pe=g._free=function(){return(pe=g._free=g.asm.Ve).apply(null,arguments)},Ba=g._malloc=function(){return(Ba=g._malloc=g.asm.We).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Xe).apply(null,arguments)};
var ve=g.___errno_location=function(){return(ve=g.___errno_location=g.asm.Ye).apply(null,arguments)},ze=g._emscripten_GetProcAddress=function(){return(ze=g._emscripten_GetProcAddress=g.asm.Ze).apply(null,arguments)},xe=g._memset=function(){return(xe=g._memset=g.asm._e).apply(null,arguments)},Ha=g.stackAlloc=function(){return(Ha=g.stackAlloc=g.asm.$e).apply(null,arguments)},we=g._memalign=function(){return(we=g._memalign=g.asm.af).apply(null,arguments)};
g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.bf).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.cf).apply(null,arguments)};g.addRunDependency=Ua;g.removeRunDependency=Va;g.FS_createPath=dc;g.FS_createDataFile=fc;g.FS_createPreloadedFile=jc;g.FS_createLazyFile=ic;g.FS_createDevice=L;g.FS_unlink=Ub;var Be;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ta=function Ce(){Be||De();Be||(Ta=Ce)};
function De(a){function b(){if(!Be&&(Be=!0,g.calledRun=!0,!za)){g.noFSInit||bc||(bc=!0,ac(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?L("/dev","stdin",g.stdin):Tb("/dev/tty","/dev/stdin"),g.stdout?L("/dev","stdout",null,g.stdout):Tb("/dev/tty","/dev/stdout"),g.stderr?L("/dev","stderr",null,g.stderr):Tb("/dev/tty1","/dev/stderr"),Wb("/dev/stdin",0),Wb("/dev/stdout",1),Wb("/dev/stderr",1));fb(Ma);Cb=!1;fb(Na);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ee){var c=a,d=g._main;
c=c||[];var e=c.length+1,f=Ha(4*(e+1));v[f>>2]=Ga(da);for(var k=1;k<e;k++)v[(f>>2)+k]=Ga(c[k-1]);v[(f>>2)+e]=0;try{var l=d(e,f);ye(l,!0)}catch(m){m instanceof pa||("unwind"==m?noExitRuntime=!0:((c=m)&&"object"===typeof m&&m.stack&&(c=[m,m.stack]),h("exception thrown: "+c),ea(1,m)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Oa.unshift(c);fb(Oa)}}a=a||ca;if(!(0<Ra)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Qa();
fb(La);0<Ra||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=De;function ye(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);za=!0}ea(a,new pa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ee=!0;g.noInitialRun&&(Ee=!1);noExitRuntime=!0;De();
